#!/usr/bin/env python3
"""Generate the layout-derived parts of the Spaceship skin set from layout/layout.json.

For every config listed under "skins" this writes, next to the skin's .ini:
  Geometry.inc  window origin/size, per-zone local origin and curved TransformationMatrix
  Meters.inc    the generic meter scaffold: [Bounds], one [Draw<n>] Shape meter per zone,
                [T<n>_<k>] text meters and [H<n>_<k>] hit meters, all carrying the zone's matrix
and in @Resources:
  Data/zones.lua    zone/keepout geometry for the Control Center's layout guard
  Offsets.inc       per-module user offsets (only created if missing, never overwritten)

Run after editing layout.json:  python tools/build.py
"""
import math
from pathlib import Path

from layoutlib import ROOT, load, matrix, shape

SKINS = ROOT / "Skins" / "Spaceship"
RES = SKINS / "@Resources"
MARGIN = 18

# texts / hits per zone for each module (zones in the order listed in layout.json "skins")
SPEC = {
    "Top\\Power": {"texts": [4], "hits": [1]},
    "Top\\Battery": {"texts": [4], "hits": [1]},
    "Top\\Console": {"texts": [16], "hits": [14]},
    "Top\\Alert": {"texts": [2], "hits": [1]},
    "Top\\GraphCPU": {"texts": [4], "hits": [1]},
    "Top\\GraphA": {"texts": [4], "hits": [1]},
    "Top\\GraphB": {"texts": [4], "hits": [1]},
    "Top\\GraphRAM": {"texts": [4], "hits": [1]},
    "Left\\Category": {"texts": [14, 0], "hits": [10, 8]},
    "Right\\Category": {"texts": [14, 0], "hits": [10, 8]},
    "Left\\Location": {"texts": [8], "hits": [1]},
    "Right\\SysInfo": {"texts": [8], "hits": [1]},
    "Left\\Upkeep": {"texts": [6], "hits": [3]},
    "Right\\Dev": {"texts": [6], "hits": [3]},
    "Center\\Target": {"texts": [5], "hits": [1]},
    "Center\\HUD": {"texts": [30], "hits": [1]},
    "Center\\Sphere": {"texts": [10], "hits": [1]},
    "Bottom\\Storage": {"texts": [10], "hits": [2]},
    "Bottom\\Audio": {"texts": [8], "hits": [6]},
    "Bottom\\Strip": {"texts": [20], "hits": [1]},
}
SPEC["Overlay\\Drawer"] = {"texts": [44], "hits": [40]}
SPEC["Overlay\\Control"] = {"texts": [110], "hits": [84]}
for i in range(1, 9):
    side = "Left" if i <= 4 else "Right"
    SPEC[f"{side}\\Slot{i}"] = {"texts": [12], "hits": [9]}


def key_of(config):
    return config.replace("\\", "")


def fnum(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def skin_geometry(layout, config, info):
    curves = layout["curves"]
    zones = {z["id"]: z for z in layout["zones"]}
    if "overlay" in info:
        o = next(o for o in layout["overlays"] if o["id"] == info["overlay"])
        return {"WX": o["x"] - MARGIN, "WY": o["y"] - MARGIN, "WW": o["w"] + 2 * MARGIN, "WH": o["h"] + 2 * MARGIN,
                "zones": [{"id": o["id"], "x": MARGIN, "y": MARGIN, "w": o["w"], "h": o["h"], "m": (1, 0, 0, 1, 0, 0)}]}
    if info.get("full"):
        return {"WX": 0, "WY": 0, "WW": layout["canvas"]["w"], "WH": layout["canvas"]["h"], "zones": []}
    if not info["zones"]:
        return {"WX": 0, "WY": 0, "WW": 1, "WH": 1, "zones": []}
    pts = [p for zid in info["zones"] for p in shape(zones[zid], curves)]
    wx = math.floor(min(p[0] for p in pts)) - MARGIN
    wy = math.floor(min(p[1] for p in pts)) - MARGIN
    ww = math.ceil(max(p[0] for p in pts)) + MARGIN - wx
    wh = math.ceil(max(p[1] for p in pts)) + MARGIN - wy
    out = []
    for zid in info["zones"]:
        z = zones[zid]
        a, b, c, d, tx, ty = matrix(z, curves)
        txw = a * wx + c * wy + tx - wx
        tyw = b * wx + d * wy + ty - wy
        out.append({"id": zid, "x": z["x"] - wx, "y": z["y"] - wy, "w": z["w"], "h": z["h"],
                    "m": (a, b, c, d, txw, tyw)})
    return {"WX": wx, "WY": wy, "WW": ww, "WH": wh, "zones": out}


def geometry_inc(config, g):
    k = key_of(config)
    lines = [
        "; GENERATED by tools/build.py from layout/layout.json - do not edit by hand.",
        "; Move or resize modules from the Control Center instead (it writes Offsets.inc).",
        "[Variables]",
        f"Module={k}",
        f"ModuleConfig=Spaceship\\{config}",
        f"WX={g['WX']}", f"WY={g['WY']}", f"WW={g['WW']}", f"WH={g['WH']}",
        f"DX=#{k}_DX#", f"DY=#{k}_DY#",
        f"ZoneCount={len(g['zones'])}",
    ]
    for n, z in enumerate(g["zones"], 1):
        a, b, c, d, tx, ty = z["m"]
        lines += [
            f"; zone {n}: {z['id']}",
            f"Z{n}={z['id']}",
            f"Z{n}_X={fnum(z['x'])}", f"Z{n}_Y={fnum(z['y'])}",
            f"Z{n}_W={fnum(z['w'])}", f"Z{n}_H={fnum(z['h'])}",
            f"Z{n}_TM={fnum(a)};{fnum(b)};{fnum(c)};{fnum(d)};({fnum(tx)}*#Scale#);({fnum(ty)}*#Scale#)",
        ]
    return "\n".join(lines) + "\n"


def meters_inc(config, g, spec):
    out = [
        "; GENERATED by tools/build.py - generic meter scaffold, driven by the module's Lua script.",
        "[Bounds]",
        "Meter=Shape",
        "Shape=Rectangle 0,0,(#WW#*#Scale#),(#WH#*#Scale#) | Fill Color 0,0,0,0 | StrokeWidth 0",
        "DynamicVariables=1",
        "",
    ]
    for n, z in enumerate(g["zones"], 1):
        out += [
            f"[Draw{n}]", "Meter=Shape", "X=0", "Y=0",
            "Shape=Rectangle 0,0,0,0 | Fill Color 0,0,0,0 | StrokeWidth 0",
            f"TransformationMatrix=#Z{n}_TM#", f"Group=Zone{n} | Draw", "DynamicVariables=1", "",
        ]
    for n, z in enumerate(g["zones"], 1):
        for t in range(1, spec["texts"][n - 1] + 1):
            out += [
                f"[T{n}_{t}]", "Meter=String", "MeterStyle=sText", "Hidden=1",
                f"TransformationMatrix=#Z{n}_TM#", f"Group=Zone{n} | Text", "",
            ]
    for n, z in enumerate(g["zones"], 1):
        for h in range(1, spec["hits"][n - 1] + 1):
            out += [
                f"[H{n}_{h}]", "Meter=Shape", "Hidden=1",
                "Shape=Rectangle 0,0,1,1 | Fill Color 0,0,0,1 | StrokeWidth 0",
                f"TransformationMatrix=#Z{n}_TM#", f"Group=Zone{n} | Hit",
                f'LeftMouseUpAction=[!CommandMeasure mScript "OnClick({n},{h})"]',
                f'RightMouseUpAction=[!CommandMeasure mScript "OnRightClick({n},{h})"]',
                f'MouseScrollUpAction=[!CommandMeasure mScript "OnScroll({n},{h},-1)"]',
                f'MouseScrollDownAction=[!CommandMeasure mScript "OnScroll({n},{h},1)"]',
                f'MouseOverAction=[!CommandMeasure mScript "OnHover({n},{h},1)"]',
                f'MouseLeaveAction=[!CommandMeasure mScript "OnHover({n},{h},0)"]',
                "",
            ]
    return "\n".join(out)


def zones_lua(layout, geoms):
    curves = layout["curves"]
    L = ["-- GENERATED by tools/build.py from layout/layout.json. Used by the layout guard.",
         "return {",
         f"  canvas = {{ w = {layout['canvas']['w']}, h = {layout['canvas']['h']} }},",
         f"  safe = {{ inset = {layout['safe_area']['inset']}, r = {layout['safe_area']['corner_radius']} }},",
         f"  gap = {layout['min_gap']},",
         f"  bottom = {layout['canvas']['h'] - layout.get('taskbar', {}).get('height', 0)},",
         "  keepouts = {"]
    for k in layout["keepouts"]:
        L.append("    { " + ", ".join(f"{{{fnum(x)}, {fnum(y)}}}" for x, y in k["poly"]) + " },")
    L.append("  },")
    L.append("  modules = {")
    zones = {z["id"]: z for z in layout["zones"]}
    for config, g in geoms.items():
        if not g["zones"] or "overlay" in layout["skins"][config]:
            continue
        polys = []
        for z in g["zones"]:
            poly = shape(zones[z["id"]], curves)
            polys.append("{ " + ", ".join(f"{{{fnum(x)}, {fnum(y)}}}" for x, y in poly) + " }")
        L.append(f'    {{ key = "{key_of(config)}", file = "{config.split(chr(92))[-1]}.ini", '
                 f'name = "{config.replace(chr(92), " ").upper()}", '
                 f'config = "Spaceship\\\\{config.replace(chr(92), chr(92) * 2)}", '
                 f'zones = {{ {", ".join(polys)} }} }},')
    L.append("  },")
    L.append("}")
    return "\n".join(L) + "\n"


def main():
    layout = load()
    geoms = {}
    for config, info in layout["skins"].items():
        g = skin_geometry(layout, config, info)
        geoms[config] = g
        folder = SKINS / config.replace("\\", "/")
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "Geometry.inc").write_text(geometry_inc(config, g), newline="\r\n")
        if config in SPEC:
            (folder / "Meters.inc").write_text(meters_inc(config, g, SPEC[config]), newline="\r\n")
    (RES / "Data").mkdir(parents=True, exist_ok=True)
    (RES / "Data" / "zones.lua").write_text(zones_lua(layout, geoms), newline="\r\n")
    offsets = RES / "Offsets.inc"
    keys = [key_of(c) for c in layout["skins"]]
    existing = offsets.read_text() if offsets.exists() else ""
    lines = existing.splitlines() if existing else [
        "; Per-module position offsets (base-canvas pixels). Written by the Control Center.",
        "[Variables]"]
    for k in keys:
        for axis in ("DX", "DY"):
            if not any(l.startswith(f"{k}_{axis}=") for l in lines):
                lines.append(f"{k}_{axis}=0")
    offsets.write_text("\n".join(lines) + "\n", newline="\r\n")
    print(f"generated geometry for {len(geoms)} modules")


if __name__ == "__main__":
    main()
