"""Bake the cockpit's neutral metal into pictures (called by tools/ship_frame.py).

Rainmeter draws a 2560x1600 image in one call; ~1500 shape paths are slower to load and can't carry a
texture. So the hull, window frames and surface detail (tools/frame_src, generated by ship_frame.py) are
rasterised here with the offline simulator, then textured with numpy:

  hull.png        textured hull (brushed-metal streaks, grime, cavity shading, depth falloff, dithering),
                  windows fully transparent
  window_mask.png white = glass, black = hull (for your own picture: tools/image_frame.py, or as a
                  Rainmeter MaskImageName)
  glass_fx.png    faint smudges and diagonal glare on the glass (white, low alpha)
  scan.png        scanlines over the glass
  shade.png       soft dark tint over the glass where the HUD sits - the darker areas of the reference,
                  instead of boxes behind the instruments

Everything theme-coloured stays live as Shape meters (Frame/Parts), so colour themes still apply.
"""
import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

import ref_layout as R

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / "Skins" / "Spaceship" / "@Resources" / "Images"
SRC = ROOT / "tools" / "frame_src"
CW, CH = R.CW, R.CH


def window_mask(feather=1.2):
    m = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(m)
    for w in R.WINDOWS:
        d.polygon([(x * R.SX, y * R.SY) for x, y in w], fill=255)
    for b in R.BEZELS:                          # the visor corner cut-offs are hull
        d.polygon([(x * R.SX, y * R.SY) for x, y in b], fill=0)
    return m.filter(ImageFilter.GaussianBlur(feather)) if feather else m


def _box(a, r, axis):
    if r < 1:
        return a
    pad = [(0, 0)] * a.ndim
    pad[axis] = (r + 1, r)
    c = np.cumsum(np.pad(a, pad, mode="edge"), axis=axis, dtype=np.float64)
    n = a.shape[axis]
    hi = np.take(c, np.arange(2 * r + 1, 2 * r + 1 + n), axis=axis)
    lo = np.take(c, np.arange(0, n), axis=axis)
    return ((hi - lo) / (2 * r + 1)).astype(np.float32)


def blur(a, sigma):
    """gaussian blur (three box passes per axis)"""
    r = int(round((math.sqrt(12 * sigma * sigma / 3 + 1) - 1) / 2))
    out = a.astype(np.float32)
    for _ in range(3):
        out = _box(_box(out, r, 0), r, 1)
    return out


def noise(seed, sigma, sx=1.0, sy=1.0):
    """smooth noise in [-1, 1]; sx / sy stretch it (brushed metal = long in x, short in y)"""
    rng = np.random.default_rng(seed)
    h, w = int(CH / sy) + 2, int(CW / sx) + 2
    n = rng.standard_normal((h, w)).astype(np.float32)
    n = blur(n, sigma)
    im = Image.fromarray(n, "F").resize((CW, CH), Image.BILINEAR)
    n = np.array(im, dtype=np.float32)
    n -= n.mean()
    return n / (np.abs(n).max() + 1e-6)


def rasterise():
    """render tools/frame_src/Frame.ini (neutral hull, frames, detail) onto a transparent canvas"""
    import rmsim
    probs = rmsim.Problems()
    sk = rmsim.Skin(SRC / "Frame.ini", "Spaceship\\FrameSrc", "full", probs, {})
    canvas = Image.new("RGBA", (CW, CH), (0, 0, 0, 0))
    rmsim.render_skin(sk, canvas, {}, probs)
    if probs.items:
        raise SystemExit(f"frame source problems: {probs.items[:5]}")
    return canvas


def _busy():
    m = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(m)
    for z in R.ZONES:
        d.polygon([tuple(p) for p in z["quad"]], fill=255)
    return np.asarray(m.filter(ImageFilter.MaxFilter(15)), dtype=np.float32) / 255


def plating():
    """panel seams cut into the big flat areas (ceiling, console, side walls), symmetric about the axis:
    returns (groove darkening, lit lip) masks in 0..1"""
    groove = Image.new("L", (CW, CH), 0)
    lip = Image.new("L", (CW, CH), 0)
    g, l = ImageDraw.Draw(groove), ImageDraw.Draw(lip)
    P = lambda x, y: (x * R.SX, y * R.SY)  # noqa: E731
    segs = []
    # ceiling: vertical cuts at mirrored offsets from the axis, one long horizontal seam
    for dx in (150, 240, 330, 455, 560):
        for sx in (-1, 1):
            segs.append((P(630 + sx * dx, 0), P(630 + sx * dx, 88)))
    segs.append((P(150, 60), P(1110, 60)))
    # console: horizontal plating bands and a centre spine
    # side walls: cuts parallel to the struts' fall line
    for x0 in (120, 260, 380):
        for sx in (-1, 1):
            a, b = P(630 + sx * (630 - x0), 520), P(630 + sx * (630 - x0 + 60), 709)
            segs.append((a, b))
    for a, b in segs:
        g.line([a, b], fill=255, width=3)
        l.line([(a[0] + 1.5, a[1] + 2), (b[0] + 1.5, b[1] + 2)], fill=255, width=1)
    busy = _busy()
    k = 1 - busy * 0.85
    return np.asarray(groove, dtype=np.float32) / 255 * k, np.asarray(lip, dtype=np.float32) / 255 * k


def highlights():
    """where the reference's metal is lit: the light colours of the owner's simplified SVG
    (art/reference-simplified.png), on the hull only, off the HUD, left half mirrored for symmetry -> 0..1"""
    ref = Image.open(ROOT / "art" / "reference-simplified.png").convert("RGB").resize((CW, CH), Image.NEAREST)
    a = np.asarray(ref, dtype=np.float32) / 255
    light = np.clip((a.mean(-1) - 0.30) / 0.45, 0, 1)
    sat = a.max(-1) - a.min(-1)
    light *= np.clip(1 - (sat - 0.35) * 4, 0, 1)            # drop saturated HUD colours
    hull = 1 - np.asarray(window_mask(0), dtype=np.float32) / 255
    hull = blur(hull, 3) > 0.98                               # stay a little off the glass edge
    light *= hull * (1 - _busy())
    half = light[:, : CW // 2]
    light = np.concatenate([half, half[:, ::-1]], axis=1)
    return np.clip(blur(light, 5) * 0.8 + blur(light, 22) * 0.6, 0, 1) * 0.35


def hull_png(base):
    rgba = np.asarray(base, dtype=np.float32)
    rgb, a = rgba[..., :3] / 255, rgba[..., 3] / 255
    lum = rgb.mean(-1)
    yy, xx = np.mgrid[0:CH, 0:CW].astype(np.float32)
    # brushed metal: fine streaks along x, a second set along the struts' diagonal, plus coarse grime
    brushed = noise(1, 1.2, sx=24, sy=1) * 0.06
    diag = Image.fromarray(noise(2, 1.2, sx=20, sy=1), "F").rotate(-52, resample=Image.BILINEAR)
    diag = np.asarray(diag, dtype=np.float32) * 0.04
    grime = noise(3, 18, sx=6, sy=6) * 0.10 + noise(4, 6, sx=3, sy=3) * 0.04
    # cavity shading: where the hull is darker than its surroundings, deepen it (seams, recesses)
    cav = np.clip(blur(lum, 5) - lum, 0, 1) * 1.6
    # depth: hull falls off toward the screen edges and the floor, like the reference's vignette
    cx, cy = CW / 2, CH * 0.42
    r = np.sqrt(((xx - cx) / (CW * 0.62)) ** 2 + ((yy - cy) / (CH * 0.75)) ** 2)
    depth = np.clip(1.0 - 0.6 * r, 0.3, 0.92)
    floor = np.clip(1 - (yy / CH - 0.78) * 1.4, 0.6, 1)
    groove, lip = plating()
    k = (1 + brushed + diag + grime - cav - groove * 0.55) * depth * floor
    out = np.clip(rgb * k[..., None], 0, 1)
    out += lip[..., None] * np.array([0.02, 0.03, 0.04], np.float32)
    # relief: light from the upper left catches every edge (emboss of the luminance)
    L = blur(lum, 1.2)
    relief = np.clip((L - np.roll(np.roll(L, 2, 0), 2, 1)) * 1.0, -0.03, 0.02)
    out = np.clip(out + relief[..., None] * np.array([0.35, 0.6, 1.0], np.float32), 0, 1)
    # fine scratches: short bright streaks, sparse
    scr = np.clip(noise(9, 0.6, sx=10, sy=1) - 0.86, 0, 1) * 1.4
    out = np.clip(out + scr[..., None] * np.array([0.01, 0.02, 0.035], np.float32), 0, 1)
    # shine: no grey speculars - a little blue light, only where the reference's metal catches light
    hi = highlights()
    out = out + hi[..., None] * np.array([0.10, 0.36, 0.85], np.float32) * 0.055
    out += (np.random.default_rng(5).random(out.shape, dtype=np.float32) - 0.5) / 255 * 1.5
    # windows: fully transparent, soft 1 px edge
    glass = np.asarray(window_mask(0.8), dtype=np.float32) / 255
    alpha = np.clip(a * (1 - glass), 0, 1)
    img = Image.fromarray(np.dstack([np.clip(out, 0, 1) * 255, alpha * 255]).astype(np.uint8), "RGBA")
    return img


def glass_fx_png():
    glass = np.asarray(window_mask(1.5), dtype=np.float32) / 255
    smudge = np.clip(noise(7, 10, sx=4, sy=4), 0, 1) ** 2 * 0.55 + np.clip(noise(8, 3, sx=2, sy=2) - 0.55, 0, 1) * 0.4
    yy, xx = np.mgrid[0:CH, 0:CW].astype(np.float32)
    glare = np.zeros((CH, CW), np.float32)
    for x0, slope, width, k in ((260, 1.05, 70, 1.0), (520, 1.05, 30, 0.6), (1620, 1.05, 90, 0.8), (1900, 1.05, 34, 0.5)):
        d = np.abs((xx - x0) - (yy * slope * 0.55)) / width
        glare += np.exp(-d * d) * k
    for x0, k in ((CW - 260, 1.0), (CW - 520, 0.6)):  # mirrored streaks on the right
        d = np.abs((xx - x0) + (yy * 0.58)) / 70
        glare += np.exp(-d * d) * k * 0.8
    alpha = np.clip(smudge * 0.10 + glare * 0.09, 0, 0.25) * glass
    img = np.dstack([np.full((CH, CW, 3), 235, np.float32), alpha * 255]).astype(np.uint8)
    return Image.fromarray(img, "RGBA")


def scan_png():
    glass = np.asarray(window_mask(1.0), dtype=np.float32) / 255
    rows = ((np.arange(CH) % 5) < 2).astype(np.float32)[:, None] * np.ones((1, CW), np.float32)
    img = np.dstack([np.zeros((CH, CW, 3), np.float32), rows * glass * 40]).astype(np.uint8)
    return Image.fromarray(img, "RGBA")


def shade_png():
    """soft dark tint: behind the HUD columns, the top console and toward the window frames"""
    m = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(m)
    for z in R.ZONES:
        if z["id"].startswith(("L_", "R_", "T_", "G")):
            d.polygon([tuple(p) for p in z["quad"]], fill=255)
    cols = np.asarray(m.filter(ImageFilter.MaxFilter(41)).filter(ImageFilter.GaussianBlur(55)), dtype=np.float32) / 255
    yy, xx = np.mgrid[0:CH, 0:CW].astype(np.float32)
    top = np.clip(1 - yy / (CH * 0.22), 0, 1) ** 1.5
    side = np.clip((np.abs(xx - CW / 2) / (CW / 2) - 0.55) / 0.45, 0, 1) ** 1.4
    glass = np.asarray(window_mask(0), dtype=np.float32) / 255
    # thicker glass near the frames reads darker
    edge = 1 - np.clip(blur(glass, 55) * 1.5 - 0.5, 0, 1)
    dark = np.clip(cols * 0.55 + top * 0.55 + side * 0.4 + edge * 0.5, 0, 0.82) * glass   # stronger edge tint
    dark = blur(dark, 6)
    img = np.dstack([np.full((CH, CW, 3), (2, 6, 10), np.float32), dark * 255]).astype(np.uint8)
    return Image.fromarray(img, "RGBA")


def mist_png():
    """neon mist: the window edges and the corner cuts, blurred very wide and kept very dim. White with an
    alpha falloff; the Frame tints it with the theme colour (ImageTint) so it follows colour themes."""
    m = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(m)
    for w in R.WINDOWS:
        pts = [(x * R.SX, y * R.SY) for x, y in w]
        d.line(pts + [pts[0]], fill=255, width=4)
    for rim in R.RIMS:
        d.line([(x * R.SX, y * R.SY) for x, y in rim], fill=255, width=6)
    a = np.asarray(m, dtype=np.float32) / 255
    a[:6, :] = a[-6:, :] = 0                    # window sides lying on the screen border are not edges
    a[:, :6] = a[:, -6:] = 0
    near, far = blur(a, 18), blur(a, 130)          # wider spread
    near /= max(1e-6, near.max()); far /= max(1e-6, far.max())
    alpha = np.clip(near * 0.055 + far * 0.065, 0, 0.10)   # weaker
    img = np.dstack([np.full((CH, CW, 3), 255, np.float32), alpha * 255]).astype(np.uint8)
    return Image.fromarray(img, "RGBA")


def sprites():
    """soft light sprites for the widgets, white with alpha (tinted at runtime with ImageTint):
    sphere_body - an even, slightly limb-brightened disc with a soft edge (smooth, no rings)
    sphere_rim  - the bright limb of the sphere, blurred
    haze        - a wide horizontal haze (target lock glow)"""
    out = {}
    n = 512
    yy, xx = np.mgrid[0:n, 0:n].astype(np.float32)
    r = np.sqrt((xx - n / 2 + 0.5) ** 2 + (yy - n / 2 + 0.5) ** 2) / (n / 2 * 0.94)
    body = np.where(r < 1, 0.80 + 0.06 * r ** 4, 0) * np.clip((1.0 - r) / 0.02, 0, 1)   # flat, even blue
    body = blur(body.astype(np.float32), 2.5)
    out["sphere_body.png"] = body
    rim = np.exp(-((r - 0.985) / 0.03) ** 2) * 0.6
    out["sphere_rim.png"] = blur(rim.astype(np.float32), 3)
    # target haze: wide and horizontal, broken into scanlines like the reference's red glow
    hy, hx = np.mgrid[0:256, 0:512].astype(np.float32)
    haze = np.exp(-(((hx - 256) / 230) ** 2 * 1.6 + ((hy - 128) / 64) ** 2 * 2.4)) * 0.95
    haze *= 1 - 0.45 * ((hy.astype(int) // 3) % 2)
    out["haze.png"] = haze
    for name, a in out.items():
        h, w = a.shape
        img = np.dstack([np.full((h, w, 3), 255, np.float32), np.clip(a, 0, 1) * 255]).astype(np.uint8)
        Image.fromarray(img, "RGBA").save(IMAGES / name, optimize=True)
    return list(out)


def corners_png():
    """the visor corner pieces, drawn over the mist so the mist only spreads inward. Colours sampled from the
    reference: near-black body, a silver-blue rim band rising to a pale highlight at the glass edge, an inner
    panel step and small vents."""
    from shapely.geometry import Point as SPoint, Polygon as SPolygon
    img = Image.new("RGBA", (CW, CH), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    bands = [(0, (150, 172, 184)), (1.2, (104, 128, 142)), (3.5, (62, 82, 96)), (8, (30, 42, 52)),
             (14, (12, 17, 22)), (22, (5, 6, 9))]
    for rim in R.RIMS:
        pts = [(x * R.SX, y * R.SY) for x, y in rim]
        # close the piece well outside the screen so only the rim side gets bands
        def ext(p):
            if p[0] <= 1:
                return (-400, p[1])
            if p[0] >= CW - 1:
                return (CW + 400, p[1])
            return (p[0], -400) if p[1] <= 1 else (p[0], CH + 400)
        corner = (-400 if pts[0][0] < CW / 2 else CW + 400, -400 if min(p[1] for p in pts) < CH / 2 else CH + 400)
        poly = SPolygon(pts + [ext(pts[-1]), corner, ext(pts[0])]).buffer(0)
        for k, col in bands:
            g = poly.buffer(-k, join_style=2)
            for q in getattr(g, "geoms", [g]):
                if not q.is_empty:
                    d.polygon([tuple(p) for p in q.exterior.coords], fill=col + (255,))
        # inner panel step: a groove with a lit lip, 40 px into the piece
        for k, col in ((40, (2, 3, 4)), (42.5, (40, 56, 66))):
            g = poly.buffer(-k, join_style=2)
            for q in getattr(g, "geoms", [g]):
                if not q.is_empty:
                    d.line([tuple(p) for p in q.exterior.coords], fill=col + (255,), width=2)
        # vents near the corner, along the rim
        from shapely.geometry import LineString as SLine
        rl = SLine(pts)
        for f in (0.30, 0.36, 0.42):
            p = rl.interpolate(f, normalized=True)
            q = rl.interpolate(min(1, f + 0.02), normalized=True)
            tx, ty = q.x - p.x, q.y - p.y
            n = max(1e-6, (tx * tx + ty * ty) ** 0.5)
            nx, ny = -ty / n, tx / n
            if not poly.contains(SPoint(p.x + nx * 60, p.y + ny * 60)):
                nx, ny = -nx, -ny                   # point the vents into the corner piece
            a = (p.x + nx * 54, p.y + ny * 54)
            b = (p.x + nx * 54 + tx / n * 26, p.y + ny * 54 + ty / n * 26)
            if 4 < a[0] < CW - 4 and 4 < a[1] < CH - 4:
                d.line([a, b], fill=(1, 1, 2, 255), width=4)
                d.line([(a[0] - nx * 2, a[1] - ny * 2), (b[0] - nx * 2, b[1] - ny * 2)], fill=(34, 46, 56, 255), width=1)
    # soften the band steps (premultiplied blur), then a soft bloom of the bright rim edge
    arr = np.asarray(img, dtype=np.float32).copy()
    pa = arr[..., 3:4] / 255
    rgb = np.stack([blur(arr[..., i] * pa[..., 0], 1.3) for i in range(3)], -1)
    al = blur(pa[..., 0], 1.3)[..., None]
    arr[..., :3] = np.where(al > 1e-3, rgb / np.maximum(al, 1e-3), 0)
    arr[..., 3] = al[..., 0] * 255
    bright = np.clip((arr[..., :3].mean(-1) - 120) / 80, 0, 1) * (arr[..., 3] / 255)
    bloom = blur(bright, 4) * 0.25
    arr[..., :3] = np.clip(arr[..., :3] + bloom[..., None] * np.array([120, 160, 180], np.float32) * (arr[..., 3:4] / 255), 0, 255)
    return Image.fromarray(arr.astype(np.uint8), "RGBA")


def render():
    IMAGES.mkdir(parents=True, exist_ok=True)
    out = {}
    hull_png(rasterise()).save(IMAGES / "hull.png", optimize=True)
    window_mask(0).convert("RGB").save(IMAGES / "window_mask.png", optimize=True)
    glass_fx_png().save(IMAGES / "glass_fx.png", optimize=True)
    scan_png().save(IMAGES / "scan.png", optimize=True)
    shade_png().save(IMAGES / "shade.png", optimize=True)
    mist_png().save(IMAGES / "mist.png", optimize=True)
    corners_png().save(IMAGES / "corners.png", optimize=True)
    sprites()
    for f in ("hull.png", "window_mask.png", "glass_fx.png", "scan.png", "shade.png", "mist.png"):
        out[f] = round((IMAGES / f).stat().st_size / 1e6, 2)
    return out


if __name__ == "__main__":
    print(render())
