#!/usr/bin/env python3
"""Generate layout/layout.json from coordinates traced off the reference image (1260 x 709).

Every zone, window and hull outline below is written in REFERENCE pixels, measured from zoomed,
gridded crops of the original cockpit image, and mapped onto the 2560 x 1600 canvas
(x * 2560/1260, y * 1600/709). Slanted panels are quads [TL, TR, BR, BL]; the build turns each quad
into a Rainmeter TransformationMatrix so text and graphics lean exactly like the reference.

Deviations from the reference are deliberate and listed in DEVIATIONS.
Run:  python tools/ref_layout.py && python tools/build.py && python tools/ship_frame.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RW, RH = 1260, 709
CW, CH = 2560, 1600
SX, SY = CW / RW, CH / RH

DEVIATIONS = [
    "Widgets stay above the Windows taskbar band (72 px); the bottom info strip sits 6 ref px higher.",
    "Symmetric layout: every right-side zone is the mirror of its left twin (owner's request); the centre column sits on the axis.",
    "Four equal app slots per side; the upkeep / dev counters sit under slot 4 / slot 8.",
]


def P(x, y):
    return [round(x * SX, 2), round(y * SY, 2)]


def rect(x0, y0, x1, y1):
    return [P(x0, y0), P(x1, y0), P(x1, y1), P(x0, y1)]


def quad(*pts):
    return [P(x, y) for x, y in pts]


def zone(zid, group, q, content):
    tl, tr, br, bl = q
    w = math.hypot(tr[0] - tl[0], tr[1] - tl[1])
    h = math.hypot(bl[0] - tl[0], bl[1] - tl[1])
    return {"id": zid, "group": group, "x": tl[0], "y": tl[1], "w": round(w, 2), "h": round(h, 2), "quad": q,
            "content": content}


def mquad(q):
    """mirror a reference quad (tl, tr, br, bl) across the vertical axis, keeping corner order"""
    tl, tr, br, bl = q
    m = lambda p: (RW - p[0], p[1])  # noqa: E731
    return (m(tr), m(tl), m(bl), m(br))


def rq(x0, y0, x1, y1):
    return ((x0, y0), (x1, y0), (x1, y1), (x0, y1))


def persp(x0, y0, x1, y1):
    """side-column zone with perspective: its horizontal edges slope toward the far vanishing point the
    reference's rails converge on (flat around y = 310, falling toward the top, rising toward the bottom)"""
    xc, yc = (x0 + x1) / 2, (y0 + y1) / 2
    s = (310 - yc) * 0.0006
    return ((x0, y0 + s * (x0 - xc)), (x1, y0 + s * (x1 - xc)), (x1, y1 + s * (x1 - xc)), (x0, y1 + s * (x0 - xc)))


# Left side + top-left half, in reference pixels: (left id, right id, group pair, quad, left content, right content).
# The right twin is generated by mirroring, so both sides always match.
PAIRS = [
    ("T_power", "T_battery", "top", ((335, 24), (432, 32), (432, 44), (335, 36)), "power draw bar", "battery bar"),
    ("G1_cpu", "G4_ram", "top", rq(333, 62, 447, 95), "CPU graph (fixed)", "RAM graph (fixed)"),
    ("G2_select", "G3_select", "top", rq(493, 62, 607, 95), "selectable graph", "selectable graph"),
    ("L_tabs", "R_tabs", "side", ((74, 39), (256, 70), (256, 91), (74, 60)), "category app tabs", "category app tabs"),
    ("L_category", "R_category", "side", persp(62, 97, 232, 218), "app wireframe", "app wireframe"),
    ("L_location", "R_sysinfo", "side", ((34, 222), (230, 232), (230, 306), (34, 296)), "LAT / LON / TZ", "ship identity"),
    ("L_dots", "R_dots", "side", persp(92, 307, 164, 321), "category page dots", "category page dots"),
    ("L_app1", "R_app1", "side", persp(34, 326, 230, 379), "slot 1", "slot 5"),
    ("L_app2", "R_app2", "side", persp(34, 389, 230, 442), "slot 2", "slot 6"),
    ("L_app3", "R_app3", "side", persp(34, 452, 230, 505), "slot 3", "slot 7"),
    ("L_app4", "R_app4", "side", persp(34, 515, 230, 566), "slot 4", "slot 8"),
    ("L_upkeep", "R_dev", "side", persp(34, 584, 84, 616), "updates / upgrades", "dev status"),
    ("B_storage", "B_audio", "bottom", rq(395, 565, 488, 638), "storage screen", "audio screen"),
    ("B_stripL", "B_stripR", "bottom", rq(425, 650, 604, 676), "info cells", "info cells"),
]
GROUPS = {"top": ("top", "top"), "side": ("left", "right"), "bottom": ("bottom", "bottom")}

ZONES = []
for lid, rid, grp, q, lc, rc in PAIRS:
    gl, gr = GROUPS[grp]
    ZONES.append(zone(lid, gl, quad(*q), lc))
    ZONES.append(zone(rid, gr, quad(*mquad(q)), rc))
ZONES += [
    # on the axis (x = 630)
    zone("T_settings", "top", rect(463, 10, 797, 57), "GPU modes + quick settings"),
    zone("T_alert", "top", rect(289, 53, 318, 72), "warning triangle + count"),
    zone("C_target", "center", rect(567, 120, 693, 216), "orange target lock"),
    zone("C_hud", "center", rect(484, 224, 776, 369), "speed ladders, pipper, M/S THR"),
    zone("C_sphere", "center", rect(514, 407, 746, 582), "holographic sphere"),
]

# ---------------------------------------------------------------- the ship (reference pixels)
# Windows from the owner's line drawing (art/window-lines-right.png: the right half, mirrored for the left).
# Drawing px -> reference px: x = 630 + gx * 630/597.7, y = (gy - 2.6) * 709/674.9
WIN_CENTER = [(333.9, 90.2), (926.1, 90.2), (759.2, 365.5), (500.8, 365.5)]
WIN_RIGHT = [(1043.1, 89.9), (1260, 303.4), (1260, 554.7), (819.4, 420.2), (782.8, 377.4)]
WIN_TOP_R = [(1116.5, 36.7), (1197.2, 0), (1260, 104.2), (1260, 181.5)]


def mirror(pts):
    return [(RW - x, y) for x, y in pts][::-1]


WIN_LEFT = mirror(WIN_RIGHT)
WIN_TOP_L = mirror(WIN_TOP_R)
WINDOWS = [WIN_CENTER, WIN_LEFT, WIN_RIGHT, WIN_TOP_L, WIN_TOP_R]


def _arc(cx, cy, rx, ry, a0, a1, n=14):
    return [(cx + rx * math.cos(math.radians(a0 + (a1 - a0) * i / n)), cy + ry * math.sin(math.radians(a0 + (a1 - a0) * i / n))) for i in range(n + 1)]


# structure between the windows (left side; the right side is mirrored)
PILLAR_L = [(216.9, 89.9), (333.9, 90.2), (500.8, 365.5), (477.2, 377.4)]       # A-pillar: windscreen | side window
STRUT_L = [(143.5, 36.7), (216.9, 89.9), (0, 303.4), (0, 181.5)]                # roof strut: side window | top window
SILL_EDGE_L = [(0, 554.7), (440.6, 420.2), (477.2, 377.4)]                      # side-window sill
PILLAR_R, STRUT_R = mirror(PILLAR_L), mirror(STRUT_L)
# visor bezel: the rounded cut-off at each screen corner (reference rim), left side; mirrored for the right
RIM_L = _arc(62, 150, 58, 150, 270, 180, 18) + [(4, 560)] + _arc(140, 560, 136, 149, 180, 90, 18)
BEZEL_L = [(0, 0)] + RIM_L + [(0, RH)]
BEZEL_R = mirror(BEZEL_L)
RIM_R = [(RW - x, y) for x, y in RIM_L]
LIGHTS = [(358, 200), (902, 200), (232, 498), (1028, 498)]
PLATES = [(330, 52, 450, 93), (490, 52, 610, 93), (660, 52, 790, 93), (825, 52, 943, 93)]
SCREENS = [(392, 562, 491, 641), (769, 562, 868, 641)]   # dash screens behind storage / audio (mirrored)
TILTED = [[(305, 648), (348, 632), (360, 694), (318, 709)], [(955, 648), (912, 632), (900, 694), (942, 709)]]
ARCH = [(383, 709), (419, 669), (500, 658), (560, 653), (630, 651), (700, 653), (760, 658), (841, 669), (877, 709)]
# lower dash lines under the arch (reference: the parallels under the cells and the outer diagonals)
DASH_LINES = [
    [(290, 706), (402, 679), (419, 669)], [(970, 706), (858, 679), (841, 669)],
    [(424, 683), (520, 671), (630, 668)], [(836, 683), (740, 671), (630, 668)],
]

# HUD lines that are part of the cockpit glass (decor layer, tinted with the theme colour)
CONSOLE_LINES = [
    [(482, 0), (510, 29), (750, 29), (778, 0)],
    [(280, 30), (445, 50), (462, 37), (602, 42), (620, 59)],
    [(642, 59), (660, 44), (800, 37), (817, 50), (980, 30)],
]
GLYPHS = [(118, 598), (148, 655), (1142, 598), (1112, 655)]
CIRCLE_GLYPH = (315, 372)
COWL_DOTS = (597.5, 662.5, 372)


def scale(pts):
    return [P(x, y) for x, y in pts]


def main():
    layout = {
        "_comment": "GENERATED by tools/ref_layout.py from the reference image (1260x709) - edit that file, not this one.",
        "deviations": DEVIATIONS,
        "reference": {"w": RW, "h": RH, "sx": SX, "sy": SY},
        "canvas": {"w": CW, "h": CH},
        "safe_area": {"inset": 10, "corner_radius": 110},
        "taskbar": {"height": 72},
        "min_gap": 6,
        "decor_gap": 1,
        "curves": {g: {"type": "flat"} for g in ("top", "left", "right", "center", "bottom")},
        "keepouts": [],
        "zones": ZONES,
        "decor": [
            {"id": f"D_glyph{i + 1}", "group": "center", "x": P(x - 7, y - 7)[0], "y": P(x - 7, y - 7)[1],
             "w": round(14 * SX, 2), "h": round(14 * SY, 2)} for i, (x, y) in enumerate(GLYPHS)
        ] + [
            {"id": f"D_circle{i + 1}", "group": "center", "x": P(cx - 9, 0)[0], "y": P(0, CIRCLE_GLYPH[1] - 9)[1],
             "w": round(18 * SX, 2), "h": round(18 * SY, 2)} for i, cx in enumerate((CIRCLE_GLYPH[0], RW - CIRCLE_GLYPH[0]))
        ] + [
            {"id": "D_tiltL", "poly": scale(TILTED[0])},
            {"id": "D_tiltR", "poly": scale(TILTED[1])},
        ],
        "overlays": [
            {"id": "O_drawer", "x": 1000, "y": 240, "w": 560, "h": 560, "content": "CARGO drawer (transient)"},
            {"id": "O_control", "x": 760, "y": 300, "w": 1040, "h": 900, "content": "Control Center (transient)"},
        ],
        "frame": {
            "windows": [scale(w) for w in WINDOWS],
            "pillars": [scale(PILLAR_L), scale(PILLAR_R)],
            "struts": [scale(STRUT_L), scale(STRUT_R)],
            "lights": scale(LIGHTS),
            "screens": [P(a, b) + P(c, d) for a, b, c, d in SCREENS],
            "tilted": [scale(t) for t in TILTED],
            "arch": scale(ARCH),
            "console_lines": [scale(l) for l in CONSOLE_LINES],
            "glyphs": scale(GLYPHS),
            "circle_glyph": P(*CIRCLE_GLYPH),
            "cowl_dots": [P(COWL_DOTS[0], COWL_DOTS[2]), P(COWL_DOTS[1], COWL_DOTS[2])],
        },
    }
    # keep the module list from the existing layout, updated for the new zones
    old = json.loads((ROOT / "layout" / "layout.json").read_text())
    skins = old["skins"]
    skins["Left\\Category"] = {"zones": ["L_tabs", "L_category", "L_dots"]}
    skins["Right\\Category"] = {"zones": ["R_tabs", "R_category", "R_dots"]}
    skins["Bottom\\Strip"] = {"zones": ["B_stripL", "B_stripR"]}
    layout["skins"] = skins
    (ROOT / "layout" / "layout.json").write_text(json.dumps(layout, indent=1))
    print(f"wrote layout.json: {len(ZONES)} zones")


if __name__ == "__main__":
    main()
