#!/usr/bin/env python3
"""Build the cockpit (Skins/Spaceship/Frame), symmetric left/right.

The windows come from the owner's line drawing (tools/ref_layout.py WINDOWS). Everything else is designed
here on the left side and mirrored, in the spirit of a real sci-fi cockpit render: gunmetal struts with
rounded shading, window frames with gaskets and bolts, lit sills, side walls with grab handles and blue LED
banks, a centre console with a hologram projector well, corrugated floor hoses.

Two outputs:
  baked  the neutral metal (Hull, Frames, Greebles) -> tools/frame_src, rasterised and textured by
         tools/frame_render.py into @Resources/Images/hull.png (+ window_mask, glass_fx, scan, shade)
  live   Shape meters in Frame/Parts that must follow the colour theme: Glass (tint), Accents (rim glow,
         LEDs, hazard marks pulled out of the baked layers), Spill, Lights, Decor (HUD lines)
Frame.ini's drawing order is regenerated too.

Metal tones are Settings.inc variables (HullDark / HullMid / HullLight / HullEdge), read when baking.
Usage: python tools/ship_frame.py
"""
import math
import random
import sys
from pathlib import Path

from shapely.affinity import scale as shp_scale
from shapely.affinity import translate as shp_translate
from shapely.geometry import LineString, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon, box
from shapely.ops import split, substring, unary_union

sys.path.insert(0, str(Path(__file__).parent))
import ref_layout as R  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PARTS = ROOT / "Skins" / "Spaceship" / "Frame" / "Parts"
FRAME_INI = PARTS.parent / "Frame.ini"
SRC_PARTS = ROOT / "tools" / "frame_src" / "Parts"
CW, CH = R.CW, R.CH
PER_METER = 150
HEADER = "; GENERATED by tools/ship_frame.py - edit the generator, not this file.\n"

DARK, MID, LIGHT, EDGE = "#HullDark#", "#HullMid#", "#HullLight#", "#HullEdge#"
ACC = "#ColorAccent#"
VECTOR_ONLY = "#UseShipImage#"


# ------------------------------------------------------------------ geometry helpers
def C(pts):
    """reference px -> canvas px"""
    return [(x * R.SX, y * R.SY) for x, y in pts]


def cpoly(pts):
    return Polygon(C(pts)).buffer(0)


def mirror(geom):
    return shp_scale(geom, -1, 1, origin=(CW / 2, 0))


def mpts(pts):
    return [(CW - x, y) for x, y in pts]


def polys_of(g):
    if g.is_empty:
        return []
    if isinstance(g, Polygon):
        return [g]
    return [p for p in getattr(g, "geoms", []) if isinstance(p, Polygon)]


def lines_of(g):
    if g.is_empty:
        return []
    if isinstance(g, LineString):
        return [g]
    if isinstance(g, MultiLineString):
        return list(g.geoms)
    out = []
    for p in getattr(g, "geoms", []):
        out += lines_of(p)
    return out


def hole_free(poly, depth=0):
    """Rainmeter paths have no holes: split polygons with interiors until none remain"""
    if not poly.interiors or depth > 12:
        return [Polygon(poly.exterior)]
    x = poly.interiors[0].centroid.x
    minx, miny, maxx, maxy = poly.bounds
    out = []
    for p in polys_of(split(poly, LineString([(x, miny - 1), (x, maxy + 1)]))):
        out += hole_free(p, depth + 1)
    return out


def norm(vx, vy):
    l = math.hypot(vx, vy) or 1.0
    return vx / l, vy / l


def at(A, B, t):
    return (A[0] + (B[0] - A[0]) * t, A[1] + (B[1] - A[1]) * t)


def grad(angle, *stops):
    return f"{angle:.0f} | " + " | ".join(f"{c} ; {o:.2f}" for c, o in stops)


# ------------------------------------------------------------------ output
class Layer:
    """Shapes for one part file, split over meters of PER_METER shapes. '{G}' in a spec is replaced by the
    shape's own gradient option name."""

    def __init__(self, name, hidden=None, redirect=None):
        # redirect: baked (neutral metal) layers hand their theme-coloured shapes to a live layer
        self.name, self.hidden, self.items, self.redirect = name, hidden, [], redirect

    def _add(self, item):
        live = self.redirect is not None and any(t in item[2] for t in (ACC, "#ColorWarn#"))
        (self.redirect.items if live else self.items).append(item)

    def path(self, pts, spec, closed=False, gradient=None):
        if len(pts) < 2:
            return
        d = " | ".join(("%.1f,%.1f" if i == 0 else "LineTo %.1f,%.1f") % p for i, p in enumerate(pts))
        if "Fill " not in spec:
            spec = "Fill Color 0,0,0,0 | " + spec     # Rainmeter fills every path white unless told otherwise
        self._add(("path", d + (" | ClosePath 1" if closed else ""), spec, gradient))

    def poly(self, geom, spec, gradient=None):
        for p in polys_of(geom):
            for q in hole_free(p):
                if q.area > 2:
                    self.path(list(q.exterior.coords)[:-1], spec, True, gradient)

    def line(self, geom, spec):
        for ln in lines_of(geom):
            self.path(list(ln.coords), spec)

    def raw(self, spec):
        self._add(("raw", None, spec, None))

    def ellipse(self, x, y, rx, ry, spec):
        self.raw(f"Ellipse {x:.1f},{y:.1f},{rx:.1f},{ry:.1f} | {spec}")

    def rect(self, x, y, w, h, spec, r=0):
        self.raw(f"Rectangle {x:.1f},{y:.1f},{w:.1f},{h:.1f}{',%.1f' % r if r else ''} | {spec}")

    def __len__(self):
        return len(self.items)

    def write(self, folder=None):
        chunks = [self.items[i:i + PER_METER] for i in range(0, len(self.items), PER_METER)] or [[]]
        out = []
        for n, chunk in enumerate(chunks, 1):
            name = self.name if len(chunks) == 1 else f"{self.name}{n:02d}"
            lines = [f"[{name}]", "Meter=Shape", "X=0", "Y=0"]
            if not chunk:
                lines.append("Shape=Rectangle 0,0,0,0 | Fill Color 0,0,0,0 | StrokeWidth 0")
            for k, (kind, d, spec, gradient) in enumerate(chunk, 1):
                key = "Shape" if k == 1 else f"Shape{k}"
                if gradient:
                    lines.append(f"G{k}={gradient}")
                    spec = spec.replace("{G}", f"G{k}")
                if kind == "path":
                    lines.append(f"P{k}={d}")
                    lines.append(f"{key}=Path P{k} | {spec}")
                else:
                    lines.append(f"{key}={spec}")
            lines.append("TransformationMatrix=#Scale#;0;0;#Scale#;0;0")
            if self.name != "Decor":
                # FrameOff=1 (cockpit art OFF) hides every layer except the HUD lines (Decor)
                lines.append(f"Hidden=(Clamp(#FrameOff#+({self.hidden or 0}),0,1))")
            elif self.hidden:
                lines.append(f"Hidden={self.hidden}")
            lines.append("DynamicVariables=0")
            out.append("\n".join(lines) + "\n")
        (folder or PARTS).mkdir(parents=True, exist_ok=True)
        ((folder or PARTS) / f"{self.name}.inc").write_text(HEADER + "\n".join(out), newline="\r\n")
        return len(self.items)


def sym_poly(layer, geom, spec, angle=None, stops=None):
    """left-side polygon + its mirror; a gradient angle is mirrored with it"""
    layer.poly(geom, spec, grad(angle, *stops) if stops else None)
    layer.poly(mirror(geom), spec, grad(180 - angle, *stops) if stops else None)


def sym_path(layer, pts, spec, closed=False):
    layer.path(pts, spec, closed)
    layer.path(mpts(pts), spec, closed)


# ------------------------------------------------------------------ the ship
SCREEN = box(0, 0, CW, CH)
BEZELS = unary_union([cpoly(b) for b in R.BEZELS])
# glass = the drawn windows minus the rounded visor bezels at the four corners
GLASS = [g for w in R.WINDOWS for g in polys_of(cpoly(w).difference(BEZELS)) if g.area > 50]
WINDOWS = unary_union(GLASS)
HULL = SCREEN.difference(WINDOWS)
ZONES = {z["id"]: Polygon(z["quad"]) for z in R.ZONES}
BUSY = unary_union(list(ZONES.values()) + [Point(*C([l])[0]).buffer(60) for l in R.LIGHTS]).buffer(10)

PILLAR = cpoly(R.PILLAR_L)
STRUT = cpoly(R.STRUT_L)
SILL_EDGE = C(R.SILL_EDGE_L)
# centre console (trapezoid widening to the floor) and the cowl under the windscreen
COWL = cpoly([(500.8, 365.5), (759.2, 365.5), (776, 393), (484, 393)])
CONSOLE = cpoly([(484, 393), (776, 393), (905, 709), (355, 709)])


def member_axis(poly_pts, a, b):
    A, B = C([a])[0], C([b])[0]
    ax = norm(B[0] - A[0], B[1] - A[1])
    return A, B, ax, (-ax[1], ax[0])


def cylinder(angle):
    """stops for a rounded metal member: dark edges, bright ridge a little off-centre"""
    return grad(angle, (f"{DARK},255", 0), (f"{MID},255", 0.28), (f"{LIGHT},255", 0.42), (f"{MID},255", 0.62), (f"{DARK},255", 1))


def build():
    rng = random.Random(11)
    # baked into hull.png by tools/frame_render.py; their theme-coloured shapes go to the live Accents layer
    accents = Layer("Accents", hidden=VECTOR_ONLY)
    hull = Layer("Hull", redirect=accents)
    frames = Layer("Frames", redirect=accents)
    greeb = Layer("Greebles", redirect=accents)
    # live Shape meters
    lights = Layer("Lights", hidden=VECTOR_ONLY)
    spill = Layer("Spill")
    glass = Layer("Glass")
    decor = Layer("Decor")

    # ---------------------------------------------------------------- glass
    for g in GLASS:
        glass.poly(g, "Fill LinearGradient GlassGrad | StrokeWidth 0")

    # ---------------------------------------------------------------- hull: silhouette, then shaded members
    hull.poly(HULL, "Fill LinearGradient {G} | StrokeWidth 0",
              grad(90, (f"{DARK},255", 0), (f"{MID},255", 0.5), (f"{DARK},255", 1)))
    left = box(0, 0, CW / 2, CH)
    # ceiling band: darker up top, catching light toward the windscreen
    ceil = box(0, 0, CW / 2, 106 * R.SY + 2).intersection(HULL).difference(STRUT)
    sym_poly(hull, ceil, "Fill LinearGradient {G} | StrokeWidth 0", 90,
             [(f"{DARK},255", 0), (f"{DARK},255", 0.6), (f"{MID},255", 1)])
    # A-pillar and roof strut, shaded as rounded members across their width
    for pts, a, b in ((R.PILLAR_L, (279.6, 97), (489, 371.5)), (R.STRUT_L, (180, 63), (0, 242))):
        A, B, ax, n = member_axis(pts, a, b)
        g, ang = cpoly(pts).intersection(HULL), math.degrees(math.atan2(n[1], n[0]))
        hull.poly(g, "Fill LinearGradient {G} | StrokeWidth 0", cylinder(ang))
        hull.poly(mirror(g), "Fill LinearGradient {G} | StrokeWidth 0", cylinder(180 - ang))
    # side wall below the side window: bands running parallel to the sill
    e0, e1 = SILL_EDGE[0], SILL_EDGE[1]
    sx, sy = norm(e1[0] - e0[0], e1[1] - e0[1])
    sn = (-sy, sx)                                                # normal pointing down into the wall
    if sn[1] < 0:
        sn = (-sn[0], -sn[1])
    wall = HULL.intersection(left).difference(CONSOLE).difference(COWL).difference(PILLAR)
    wall = wall.difference(Polygon([(0, 0), (CW / 2, 0), (CW / 2, e1[1]), e1, e0, (0, e0[1])]))
    sill_ang = math.degrees(math.atan2(sn[1], sn[0]))
    bands = [(0, 30, [(f"{LIGHT},255", 0), (f"{MID},255", 0.45), (f"{DARK},255", 1)]),        # lit sill top
             (30, 150, [(f"{MID},255", 0), (f"{DARK},255", 1)]),                                # upper wall panel
             (150, 290, [(f"{DARK},255", 0), (f"{MID},235", 0.5), (f"{DARK},255", 1)]),          # lower wall panel
             (290, 900, [(f"{DARK},255", 0), (f"0,0,0,255", 1)])]                               # floor shadow
    band_lines = []
    for d0, d1, stops in bands:
        strip = Polygon([(e0[0] - sx * 3000 + sn[0] * d0, e0[1] - sy * 3000 + sn[1] * d0),
                         (e0[0] + sx * 3000 + sn[0] * d0, e0[1] + sy * 3000 + sn[1] * d0),
                         (e0[0] + sx * 3000 + sn[0] * d1, e0[1] + sy * 3000 + sn[1] * d1),
                         (e0[0] - sx * 3000 + sn[0] * d1, e0[1] - sy * 3000 + sn[1] * d1)])
        sym_poly(hull, wall.intersection(strip), "Fill LinearGradient {G} | StrokeWidth 0", sill_ang, stops)
        if d0 > 0:
            band_lines.append(d0)
    # console and cowl
    hull.poly(CONSOLE, "Fill LinearGradient {G} | StrokeWidth 0",
              grad(90, (f"{MID},255", 0), (f"{DARK},255", 0.55), (f"0,0,0,255", 1)))
    hull.poly(COWL, "Fill LinearGradient {G} | StrokeWidth 0",
              grad(90, (f"{LIGHT},255", 0), (f"{MID},255", 0.4), (f"{DARK},255", 1)))
    # console side bevels
    for pts in (C([(484, 393), (355, 709)]), ):
        sym_path(hull, pts, f"Stroke Color {LIGHT},150 | StrokeWidth 2.2")
        sym_path(hull, [(x + 6, y) for x, y in pts], "Stroke Color 0,0,0,170 | StrokeWidth 3")
    hull.path(C([(484, 393), (776, 393)]), "Stroke Color 0,0,0,180 | StrokeWidth 3")
    hull.path(C([(500.8, 366.5), (759.2, 366.5)]), f"Stroke Color {EDGE},170 | StrokeWidth 2")
    # wall seams between the bands (groove + lit lip), clipped off widgets
    for d in band_lines[:2]:
        ln = LineString([(e0[0] - sx * 3000 + sn[0] * d, e0[1] - sy * 3000 + sn[1] * d),
                         (e0[0] + sx * 3000 + sn[0] * d, e0[1] + sy * 3000 + sn[1] * d)]).intersection(wall)
        for seg in lines_of(ln):
            pts = list(seg.coords)
            sym_path(hull, pts, "Stroke Color 0,0,0,190 | StrokeWidth 3")
            sym_path(hull, [(x + sn[0] * 2.5, y + sn[1] * 2.5) for x, y in pts], f"Stroke Color {LIGHT},110 | StrokeWidth 1.2")

    # long glossy reflections running along the lower wall, parallel to the sill (reference beam highlights)
    for down, w, al in ((58, 3.0, 34), (66, 1.4, 26), (150, 2.4, 22), (232, 1.6, 16)):
        ln = LineString([(e0[0] - sx * 200 + sn[0] * down, e0[1] - sy * 200 + sn[1] * down),
                         (e0[0] + sx * 1400 + sn[0] * down, e0[1] + sy * 1400 + sn[1] * down)])
        for s_ in lines_of(ln.intersection(wall.buffer(-10)).difference(BUSY)):
            if s_.length < 120:
                continue
            pts = list(s_.coords)
            sym_path(hull, pts, f"Stroke Color 140,180,210,{al} | StrokeWidth {w}")

    # ---------------------------------------------------------------- window edges (owner's crops): a tube rail along
    # the glass, a thin second rail, two cables sagging between clamps, a red strip under the side-window sills;
    # no bolts. Not on edges that lie on the screen border or under the corner pieces.
    excl = SCREEN.difference(SCREEN.buffer(-4)).union(BEZELS.buffer(8))

    def rail(k):
        out = []
        for wp in GLASS:
            ring = wp.buffer(k, join_style=2).exterior.difference(excl)
            out += [(wp, ln) for ln in lines_of(ring) if ln.length > 30]
        return out

    for wp, ln in rail(7):
        pts = list(ln.coords)
        frames.path(pts, "Stroke Color 0,0,0,230 | StrokeWidth 15 | StrokeLineJoin Round")
        frames.path(pts, f"Stroke Color {MID},255 | StrokeWidth 11 | StrokeLineJoin Round")
    for wp, ln in rail(4.5):
        frames.path(list(ln.coords), f"Stroke Color {LIGHT},255 | StrokeWidth 2.6 | StrokeLineJoin Round")
    for wp, ln in rail(8.5):   # crisp silver catch-light on the tube rail (reference: pale glossy rails at every window edge)
        frames.path(list(ln.coords), "Stroke Color 178,194,210,150 | StrokeWidth 1.3 | StrokeLineJoin Round")
    for wp, ln in rail(2.2):
        frames.path(list(ln.coords), f"Stroke Color {EDGE},70 | StrokeWidth 1 | StrokeLineJoin Round")
    for wp, ln in rail(19):
        pts = list(ln.coords)
        frames.path(pts, "Stroke Color 0,0,0,210 | StrokeWidth 6 | StrokeLineJoin Round")
        frames.path(pts, f"Stroke Color {MID},255 | StrokeWidth 3 | StrokeLineJoin Round")
    # cables: sample along the rail, sag outward between clamps every 150 px
    for k, amp in ((12, 3.5), (26, 5)):
        for wp, ln in rail(k):
            outer = wp.buffer(k + 1)
            pts, d = [], 0.0
            while d <= ln.length:
                p, q = ln.interpolate(d), ln.interpolate(min(ln.length, d + 2))
                tx, ty = norm(q.x - p.x, q.y - p.y)
                nx, ny = -ty, tx
                if outer.contains(Point(p.x + nx * 3, p.y + ny * 3)):
                    nx, ny = -nx, -ny
                sag = amp * math.sin(math.pi * (d % 150) / 150)
                pts.append((p.x + nx * sag, p.y + ny * sag))
                d += 6
            frames.path(pts, "Stroke Color 3,4,6,255 | StrokeWidth 2.6 | StrokeLineJoin Round")
            frames.path([(x, y - 1) for x, y in pts], f"Stroke Color {LIGHT},70 | StrokeWidth 0.8")
    # clamps across the rails where the cables are tied
    for wp, ln in rail(14):
        d = 75.0
        while d < ln.length - 20:
            p, q = ln.interpolate(d), ln.interpolate(d + 2)
            tx, ty = norm(q.x - p.x, q.y - p.y)
            nx, ny = -ty, tx
            a_, b_ = (p.x - nx * 12, p.y - ny * 12), (p.x + nx * 15, p.y + ny * 15)
            frames.path([a_, b_], "Stroke Color 0,0,0,230 | StrokeWidth 7")
            frames.path([a_, b_], f"Stroke Color {LIGHT},255 | StrokeWidth 3")
            d += 150
    # red accent strip under the side-window rails (second crop)
    sill = R.SILL_EDGE_L[:2]                     # the long sill only, not the turn up to the windscreen corner
    sill = [sill[0], (sill[0][0] + (sill[1][0] - sill[0][0]) * 0.93, sill[0][1] + (sill[1][1] - sill[0][1]) * 0.93)]
    for pts in (C(sill), mpts(C(sill))):
        strip = LineString([(x, y + 36) for x, y in pts]).difference(excl).intersection(HULL.buffer(-2))
        frames.line(strip, "Stroke Color 150,26,30,210 | StrokeWidth 3")
        frames.line(strip, "Stroke Color 255,90,90,60 | StrokeWidth 1")
    # lamps (reference close-ups): each light is a grey cylinder with a round hole through it, running into a
    # black cylinder that ends in a black cone; the cone's base is narrower than the cylinder, so a polished
    # ring of the cylinder's end face shows (and reflects the light) around it, and the light shines out of the
    # cone's tip. One rides the A-pillar pointing down it; one sits on the long tube under each side window
    # pointing in toward the centre. Mirrored for the right side.
    def beam(X, Y, ux, uy, length, r, side):
        # the long beam under the side window that carries the lamp (reference: one smooth, dark, glossy member
        # with a bright catch-light along its top and a soft reflection underneath - no segments)
        if side:
            X, ux = CW - X, -ux
        nx, ny = -uy, ux
        if ny > 0:
            nx, ny = -nx, -ny                                     # n points up the screen (the lit top)
        ex, ey = X + ux * length, Y + uy * length
        body = [(X + nx * r, Y + ny * r), (ex + nx * r * 0.8, ey + ny * r * 0.8), (ex - nx * r * 0.8, ey - ny * r * 0.8),
                (X - nx * r, Y - ny * r)]
        ang = math.degrees(math.atan2(-ny, -nx))
        frames.path(body, "Fill LinearGradient {G} | Stroke Color 0,0,0,230 | StrokeWidth 2", True,
                    grad(ang, ("62,74,88,255", 0), ("24,29,36,255", 0.12), ("10,12,16,255", 0.45), ("30,37,46,255", 0.72),
                         ("74,88,104,255", 0.86), ("8,10,13,255", 1)))
        frames.path([(X + nx * r * 0.82, Y + ny * r * 0.82), (ex + nx * r * 0.66, ey + ny * r * 0.66)],
                    "Stroke Color 196,214,230,170 | StrokeWidth 1.6")
        frames.path([(X - nx * r * 0.55, Y - ny * r * 0.55), (ex - nx * r * 0.45, ey - ny * r * 0.45)],
                    "Stroke Color 120,150,180,60 | StrokeWidth 5")
        frames.path([(ex + nx * r * 0.8, ey + ny * r * 0.8), (ex - nx * r * 0.8, ey - ny * r * 0.8)], "Stroke Color 0,0,0,230 | StrokeWidth 3")

    def lamp(X, Y, ux, uy, r, side):
        # (X, Y) = the cone tip the light leaves from; u = the direction the light points
        if side:
            X, ux = CW - X, -ux
        nx, ny = -uy, ux
        ang = math.degrees(math.atan2(ny, nx))
        e = 0.38                                                   # how open the round faces look (view angle)

        def P(t, s_):                                              # t: distance back from the tip, s_: across
            return (X - ux * t + nx * s_, Y - uy * t + ny * s_)

        def ring(t, a, th0, th1, n=24):                            # th in degrees; sin > 0 = further back
            return [P(t + e * a * math.sin(math.radians(th0 + (th1 - th0) * i / n)),
                      a * math.cos(math.radians(th0 + (th1 - th0) * i / n))) for i in range(n + 1)]

        def segment(t0, t1, a):                                    # a cylinder between two stations
            return ring(t0, a, 0, -180) + ring(t1, a, 180, 0)

        Lc, Lb, Lg = r * 0.95, r * 1.25, r * 1.7                   # cone, black cylinder, grey cylinder lengths
        shade = lambda *st: grad(ang, *st)
        # grey cylinder (furthest from the light) with a round hole through its side
        frames.path(segment(Lc + Lb, Lc + Lb + Lg, r * 0.96), "Fill LinearGradient {G} | Stroke Color 0,0,0,220 | StrokeWidth 1.6",
                    True, shade(("40,44,50,255", 0), ("120,126,134,255", 0.2), ("188,194,200,255", 0.38), ("150,156,164,255", 0.6),
                                ("78,84,92,255", 0.82), ("30,33,38,255", 1)))
        hc = P(Lc + Lb + Lg * 0.52, -r * 0.12)
        hole = H_ellipse(hc[0], hc[1], r * 0.30, r * 0.36, ang)
        frames.path(hole, "Fill Color 6,7,9,255 | Stroke Color 40,44,50,255 | StrokeWidth 1.2", True)
        frames.path(H_ellipse(hc[0], hc[1], r * 0.30, r * 0.36, ang, 20, 160, 16), "Stroke Color 220,226,232,170 | StrokeWidth 1.4")
        # black cylinder, glossy line along it
        frames.path(segment(Lc, Lc + Lb, r), "Fill LinearGradient {G} | Stroke Color 0,0,0,240 | StrokeWidth 1.6", True,
                    shade(("4,5,7,255", 0), ("26,30,36,255", 0.25), ("70,80,92,255", 0.36), ("18,21,26,255", 0.5), ("6,7,9,255", 1)))
        frames.path([P(Lc + r * 0.25, -r * 0.42), P(Lc + Lb - r * 0.1, -r * 0.42)], "Stroke Color 150,175,200,120 | StrokeWidth 1.4")
        # polished end face of the black cylinder: the ring left showing around the cone's base, catching the light
        face = ring(Lc, r, 0, 360, 40)
        frames.path(face, "Fill LinearGradient {G} | Stroke Color 0,0,0,230 | StrokeWidth 1.4", True,
                    shade(("70,84,100,255", 0), ("210,226,240,255", 0.3), ("120,150,190,255", 0.5), ("235,244,252,255", 0.68),
                          ("60,72,88,255", 1)))
        # black cone from that face out to the tip
        rb, rt = r * 0.70, r * 0.36
        cone = ring(0, rt, 0, -180) + ring(Lc, rb, 180, 0)
        frames.path(ring(Lc, rb, 0, 360, 32), "Fill Color 4,5,7,255 | StrokeWidth 0", True)
        frames.path(cone, "Fill LinearGradient {G} | Stroke Color 0,0,0,240 | StrokeWidth 1.2", True,
                    shade(("2,3,4,255", 0), ("22,26,32,255", 0.3), ("60,70,84,255", 0.42), ("12,14,18,255", 0.6), ("2,3,4,255", 1)))
        # the lens at the tip (the light itself is live, in the Lights layer, centred here)
        frames.path(ring(0, rt, 0, 360, 24), "Fill Color 20,40,70,255 | Stroke Color 120,160,200,200 | StrokeWidth 1.2", True)

    def H_ellipse(cx_, cy_, rx, ry, rot, a0=0, a1=360, n=36):
        cr, sr = math.cos(math.radians(rot)), math.sin(math.radians(rot))
        out = []
        for i in range(n + 1):
            t = math.radians(a0 + (a1 - a0) * i / n)
            x_, y_ = rx * math.cos(t), ry * math.sin(t)
            out.append((cx_ + x_ * cr - y_ * sr, cy_ + x_ * sr + y_ * cr))
        return out

    pu = norm((500.8 - 342.3) * R.SX, (365.5 - 104) * R.SY)          # down the A-pillar
    su = norm(440.6 * R.SX, -134.5 * R.SY)                            # along the sill, toward the centre
    for side in (0, 1):
        lamp(358 * R.SX, 200 * R.SY, pu[0], pu[1], 26, side)            # points down the pillar, body above it
        # the side-window lamp points in toward the centre; the long tube runs on behind it
        bx, by = 232 * R.SX - su[0] * 70, 498 * R.SY - su[1] * 70
        beam(bx + su[0] * 20, by + su[1] * 20 + 8, su[0], su[1], 360, 24, side)
        # the second, lower member under it (reference: a broad grey structure with a soft pale reflection)
        lx, ly = 232 * R.SX + su[0] * 150, 498 * R.SY + su[1] * 150 + 96
        q0 = (lx if side == 0 else CW - lx, ly)
        ux_ = su[0] if side == 0 else -su[0]
        q1 = (q0[0] + ux_ * 470, q0[1] + su[1] * 470)
        for off, w, al in ((0, 30, 255), (-4, 10, 255), (-7, 3, 255)):
            col = ("10,12,16", "52,62,74", "150,170,190")[[30, 10, 3].index(w)]
            a_ = 0.9 if w == 30 else (0.55 if w == 10 else 0.45)
            frames.path([(q0[0], q0[1] + off), (q1[0], q1[1] + off)], f"Stroke Color {col},{int(al * a_)} | StrokeWidth {w} | StrokeStartCap Round | StrokeEndCap Round")
        lamp(232 * R.SX, 498 * R.SY, su[0], su[1], 26, side)
        # loose cables looping past the pillar lamp on the outer side
        loop = [(306, 140), (316, 168), (326, 200), (342, 230), (368, 252), (398, 266), (426, 302), (452, 336)]
        pts = C(loop) if side == 0 else mpts(C(loop))
        frames.path(pts, "Stroke Color 0,0,0,230 | StrokeWidth 3.4 | StrokeLineJoin Round")
        frames.path([(x, y - 1) for x, y in pts], f"Stroke Color {LIGHT},150 | StrokeWidth 1.2 | StrokeLineJoin Round")

    # ---------------------------------------------------------------- visor bezels: the rounded corner cut-offs
    # baked: a dark rolled lip just outside the rim; live (Accents): blue light bleeding off the rim edge
    # (the corner pieces themselves are baked by frame_render.corners_png and drawn over the mist)

    # ---------------------------------------------------------------- pillar / strut detail
    # the A-pillar is a smooth tube in the reference (no seams or vents); only the roof strut keeps its panels
    members = [(R.STRUT_L, (180, 63), (0, 242), (0.3, 0.75), None)]
    for pts, a, b, seams, vent in members:
        poly = cpoly(pts).intersection(HULL)
        A, B, ax, n = member_axis(pts, a, b)
        for side in (0, 1):
            P_ = poly if side == 0 else mirror(poly)
            A_ = A if side == 0 else (CW - A[0], A[1])
            B_ = B if side == 0 else (CW - B[0], B[1])
            ax_ = ax if side == 0 else (-ax[0], ax[1])
            n_ = n if side == 0 else (-n[0], n[1])
            for off, spec in ((-24, "Stroke Color 0,0,0,130 | StrokeWidth 1.8"), (-25.8, f"Stroke Color {LIGHT},45 | StrokeWidth 0.8")):
                for p in polys_of(P_.buffer(off, join_style=2)):
                    greeb.line(p.exterior.difference(BUSY), spec)
            for t in seams:
                c = at(A_, B_, t)
                seg = LineString([(c[0] - n_[0] * 400, c[1] - n_[1] * 400), (c[0] + n_[0] * 400, c[1] + n_[1] * 400)]).intersection(P_.buffer(-14))
                for s in lines_of(seg):
                    if s.intersects(BUSY):
                        continue
                    p0, p1 = s.coords[0], s.coords[-1]
                    greeb.path([p0, p1], "Stroke Color 0,0,0,190 | StrokeWidth 2.6")
                    greeb.path([(p0[0] + ax_[0] * 2.4, p0[1] + ax_[1] * 2.4), (p1[0] + ax_[0] * 2.4, p1[1] + ax_[1] * 2.4)],
                               f"Stroke Color {LIGHT},90 | StrokeWidth 1")
            if vent:
                c0, c1 = at(A_, B_, vent[0]), at(A_, B_, vent[1])
                plate = P_.buffer(-28).intersection(LineString([c0, c1]).buffer(40, cap_style=2))
                if plate.geom_type == "Polygon" and not plate.intersects(BUSY) and plate.area > 200:
                    greeb.poly(plate, "Fill Color 0,0,0,110 | Stroke Color 0,0,0,180 | StrokeWidth 1.4")
                    m = max(4, int(math.dist(c0, c1) / 10))
                    for i in range(m):
                        c = at(c0, c1, (i + 0.5) / m)
                        seg = LineString([(c[0] - n_[0] * 200, c[1] - n_[1] * 200), (c[0] + n_[0] * 200, c[1] + n_[1] * 200)]).intersection(plate.buffer(-5))
                        for s in lines_of(seg):
                            p0, p1 = s.coords[0], s.coords[-1]
                            greeb.path([p0, p1], "Stroke Color 0,0,0,230 | StrokeWidth 3.4 | StrokeStartCap Round | StrokeEndCap Round")
                            greeb.path([(p0[0] + ax_[0] * 2.4, p0[1] + ax_[1] * 2.4), (p1[0] + ax_[0] * 2.4, p1[1] + ax_[1] * 2.4)],
                                       f"Stroke Color {LIGHT},60 | StrokeWidth 1")

    # ---------------------------------------------------------------- side walls: grab handles, LED clusters, vents
    def wall_point(d_along, d_down):
        return (e0[0] + sx * d_along + sn[0] * d_down, e0[1] + sy * d_along + sn[1] * d_down)

    def handle(p0, p1):
        for side in (0, 1):
            q0, q1 = (p0, p1) if side == 0 else ((CW - p0[0], p0[1]), (CW - p1[0], p1[1]))
            bar = [q0, q1]
            greeb.path(bar, "Stroke Color 0,0,0,170 | StrokeWidth 15 | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path(bar, f"Stroke Color {MID},255 | StrokeWidth 10 | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path([(x, y - 2.2) for x, y in bar], f"Stroke Color {EDGE},150 | StrokeWidth 2.4 | StrokeStartCap Round | StrokeEndCap Round")
            for q in (q0, q1):
                greeb.rect(q[0] - 9, q[1] - 6, 18, 16, f"Fill Color {DARK},255 | Stroke Color 0,0,0,200 | StrokeWidth 1.2", 2)
                greeb.ellipse(q[0], q[1] + 2, 2.4, 2.4, f"Fill Color {LIGHT},160 | StrokeWidth 0")

    taken = []

    def free(x, y=None, w=None, h=None):
        g = x if y is None else box(x, y, x + w, y + h)
        return (HULL.buffer(-6).contains(g) and not g.intersects(BUSY) and g.intersects(wall)
                and not any(g.buffer(30).intersects(t) for t in taken))

    for along in [150] + list(range(0, 900, 40)):
        q0, q1 = wall_point(along, 95), wall_point(along + 260, 95)
        bar = LineString([q0, q1]).buffer(14)
        if free(bar):
            handle(q0, q1)
            taken.append(bar)
            break
    # ---------------------------------------------------------------- console: projector well, button banks, hazard edge
    cx, wy = 630 * R.SX, 588 * R.SY
    for rx, ry, spec in ((240, 52, f"Fill Color 0,0,0,200 | Stroke Color {LIGHT},90 | StrokeWidth 2"),
                         (205, 42, f"Fill Color {DARK},255 | Stroke Color 0,0,0,220 | StrokeWidth 3"),
                         (170, 33, f"Fill Color 0,0,0,230 | Stroke Color {ACC},120 | StrokeWidth 2"),
                         (120, 22, f"Fill Color 0,6,12,255 | Stroke Color {ACC},200 | StrokeWidth 2.5")):
        hull.ellipse(cx, wy, rx, ry, spec)
    for k in range(24):
        a = k / 24 * math.tau
        x0, y0 = cx + math.cos(a) * 178, wy + math.sin(a) * 36
        x1, y1 = cx + math.cos(a) * 196, wy + math.sin(a) * 40
        hull.path([(x0, y0), (x1, y1)], f"Stroke Color {LIGHT},80 | StrokeWidth 1.4")
    spill.ellipse(cx, wy, 150, 26, f"Fill Color {ACC},28 | StrokeWidth 0")
    spill.ellipse(cx, wy, 95, 15, f"Fill Color {ACC},60 | StrokeWidth 0")
    spill.ellipse(cx, wy, 40, 6, "Fill Color 220,250,255,140 | StrokeWidth 0")
    # console face: vertical grille slats (reference), then the metal pedestal under the arch
    gx0, gx1 = 515 * R.SX, 745 * R.SX
    x = gx0
    while x <= gx1:
        seg = LineString([(x, 400 * R.SY), (x, 600 * R.SY)]).intersection(CONSOLE.buffer(-14))
        frames.line(seg, "Stroke Color 0,0,0,150 | StrokeWidth 2.2")
        frames.line(shp_translate(seg, 2, 0), f"Stroke Color {LIGHT},40 | StrokeWidth 1")
        x += 11
    ped = [(612, 709), (614, 662), (622, 652), (638, 652), (646, 662), (648, 709)]
    hull.poly(cpoly(ped), "Fill LinearGradient {G} | Stroke Color 0,0,0,230 | StrokeWidth 2",
              grad(0, ("18,22,28,255", 0), ("88,104,120,255", 0.35), ("150,170,186,255", 0.5), ("70,84,98,255", 0.7), ("16,20,26,255", 1)))
    hull.path(C([(622, 653), (638, 653)]), "Stroke Color 190,215,230,120 | StrokeWidth 2")
    hull.path(C([(630, 655), (630, 709)]), "Stroke Color 0,0,0,120 | StrokeWidth 2")

    # ---------------------------------------------------------------- corrugated hoses along the floor
    def hose(pts, width):
        path = LineString(pts)
        for side in (0, 1):
            P_ = path if side == 0 else LineString(mpts(list(path.coords)))
            c = list(P_.coords)
            greeb.path(c, f"Stroke Color 0,0,0,220 | StrokeWidth {width + 6} | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path(c, f"Stroke Color {DARK},255 | StrokeWidth {width} | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path([(x, y - width * 0.22) for x, y in c], f"Stroke Color {MID},255 | StrokeWidth {width * 0.35:.1f}")
            d = 6.0
            while d < P_.length:
                p, q = P_.interpolate(d), P_.interpolate(min(P_.length, d + 1))
                tx, ty = norm(q.x - p.x, q.y - p.y)
                nx, ny = -ty, tx
                h = width / 2
                greeb.path([(p.x - nx * h, p.y - ny * h), (p.x + nx * h, p.y + ny * h)], "Stroke Color 0,0,0,200 | StrokeWidth 2.2")
                greeb.path([(p.x - nx * h + tx * 2.5, p.y - ny * h + ty * 2.5), (p.x + nx * h + tx * 2.5, p.y + ny * h + ty * 2.5)],
                           f"Stroke Color {LIGHT},70 | StrokeWidth 1")
                d += 11

    hose(C([(150, 712), (230, 688), (310, 684), (352, 700), (365, 712)]), 26)
    hose(C([(60, 715), (120, 694), (210, 676), (250, 664)]), 18)

    # ---------------------------------------------------------------- detail pass (reference comparison): panel tone
    # changes, white marks (blank placards, tick marks, specular glints), small red/amber markers and extra
    # shapes. Everything is placed on the left and mirrored, so the ship stays symmetrical.
    drng = random.Random(23)
    TONES = [("0,0,0", 70), ("10,14,20", 85), ("28,34,42", 60), ("40,50,62", 45), ("60,74,90", 26),
             ("50,45,42", 38), ("22,30,40", 70)]

    def patch(g, tone):
        for gp in polys_of(g):
            if gp.area < 900:
                continue
            col, a = tone
            sym_poly(hull, gp, f"Fill Color {col},{a} | Stroke Color 0,0,0,150 | StrokeWidth 1.6")
            sym_path(hull, list(gp.exterior.coords), f"Stroke Color {LIGHT},34 | StrokeWidth 1", True)

    # side wall: cells between lines parallel to the sill and lines across it
    alongs, downs = [-260, -40, 150, 330, 520, 700, 880, 1060], [36, 100, 160, 228, 300, 390, 520]
    for i in range(len(alongs) - 1):
        for j in range(len(downs) - 1):
            if drng.random() < 0.38:
                continue
            a0, a1, d0, d1 = alongs[i], alongs[i + 1], downs[j], downs[j + 1]
            cell = Polygon([wall_point(a0, d0), wall_point(a1, d0), wall_point(a1, d1), wall_point(a0, d1)])
            patch(cell.intersection(wall.buffer(-3)), drng.choice(TONES))
    # ceiling: a row of plates of different shades
    xs = [0, 120, 230, 330, 440, 560, 630]
    for i in range(len(xs) - 1):
        if drng.random() < 0.3:
            continue
        cell = box(xs[i] * R.SX, 0, xs[i + 1] * R.SX, 104 * R.SY)
        patch(cell.intersection(ceil.buffer(-3)).difference(BUSY), drng.choice(TONES))
    # console flanks
    for (x0, y0, x1, y1) in ((372, 400, 420, 470), (420, 400, 470, 440), (395, 470, 450, 560)):
        g = cpoly([(x0, y0), (x1, y0), (x1, y1), (x0, y1)]).intersection(HULL.buffer(-4)).difference(BUSY).difference(WINDOWS)
        patch(g, drng.choice(TONES))

    def rrect(cx_, cy_, ux_, uy_, w_, h_):
        nx_, ny_ = -uy_, ux_
        return [(cx_ - ux_ * w_ / 2 - nx_ * h_ / 2, cy_ - uy_ * w_ / 2 - ny_ * h_ / 2), (cx_ + ux_ * w_ / 2 - nx_ * h_ / 2, cy_ + uy_ * w_ / 2 - ny_ * h_ / 2),
                (cx_ + ux_ * w_ / 2 + nx_ * h_ / 2, cy_ + uy_ * w_ / 2 + ny_ * h_ / 2), (cx_ - ux_ * w_ / 2 + nx_ * h_ / 2, cy_ - uy_ * w_ / 2 + ny_ * h_ / 2)]

    AVOID = unary_union([BUSY] + [Point(*C([g_])[0]).buffer(160) for g_ in R.GLYPHS])   # widgets and HUD glyphs stay clean

    def ok(pts, pad=4):
        g = MultiPoint(pts).convex_hull.buffer(1)
        return HULL.buffer(-pad).contains(g) and not g.intersects(AVOID)

    def placard(cx_, cy_, ux_, uy_, w_, h_, lines_=2):
        # a blank white placard: plate, dark rule lines where the text would be (no words)
        pts = rrect(cx_, cy_, ux_, uy_, w_, h_)
        if not ok(pts):
            return False
        sym_path(greeb, pts, "Fill Color 214,222,230,165 | Stroke Color 0,0,0,170 | StrokeWidth 1", True)
        nx_, ny_ = -uy_, ux_
        for k in range(lines_):
            off = (k - (lines_ - 1) / 2) * h_ / (lines_ + 0.6)
            ln_w = w_ * (0.7 if k == 0 else 0.45)
            sym_path(greeb, [(cx_ - ux_ * ln_w / 2 + nx_ * off, cy_ - uy_ * ln_w / 2 + ny_ * off),
                             (cx_ + ux_ * ln_w / 2 + nx_ * off, cy_ + uy_ * ln_w / 2 + ny_ * off)], "Stroke Color 30,36,44,200 | StrokeWidth 1.3")
        return True

    def ticks(cx_, cy_, ux_, uy_, n=3, ln_=12, gap=6, col="225,232,240", a=190):
        nx_, ny_ = -uy_, ux_
        segs = []
        for k in range(n):
            o = (k - (n - 1) / 2) * gap
            segs.append([(cx_ + ux_ * o - nx_ * ln_ / 2, cy_ + uy_ * o - ny_ * ln_ / 2), (cx_ + ux_ * o + nx_ * ln_ / 2, cy_ + uy_ * o + ny_ * ln_ / 2)])
        if not ok([pt for sg in segs for pt in sg], 3):
            return False
        for sg in segs:
            sym_path(greeb, sg, f"Stroke Color {col},{a} | StrokeWidth 2.2")
        return True

    def marker(cx_, cy_, col):
        if not ok(rrect(cx_, cy_, 1, 0, 14, 14), 3):
            return
        for side in (0, 1):
            x_ = cx_ if side == 0 else CW - cx_
            greeb.rect(x_ - 5, cy_ - 3, 10, 6, "Fill Color 0,0,0,220 | StrokeWidth 0", 1)
            greeb.rect(x_ - 3.5, cy_ - 1.6, 7, 3.2, f"Fill Color {col},235 | StrokeWidth 0", 1)
            greeb.ellipse(x_, cy_, 9, 5, f"Fill Color {col},38 | StrokeWidth 0")

    # placards and ticks on the A-pillar, roof strut, sill wall and console flanks
    pdir = (pu[0], pu[1])
    for t, off in ((0.62, -26), (0.8, -24)):
        px_, py_ = at(C([(342.3, 104)])[0], C([(500.8, 365.5)])[0], t)
        placard(px_ - pdir[1] * off, py_ + pdir[0] * off, pdir[0], pdir[1], 30, 13)
    for t in (0.35, 0.92):
        px_, py_ = at(C([(342.3, 104)])[0], C([(500.8, 365.5)])[0], t)
        ticks(px_ + pdir[1] * 24, py_ - pdir[0] * 24, pdir[0], pdir[1])
    sdir = (sx, sy)
    placed = 0
    for along in range(80, 1100, 37):
        for down in (48, 132, 196, 262):
            if placed < 4 and placard(*wall_point(along, down), *sdir, 34 + 8 * (placed % 2), 14, 2 + placed % 2):
                placed += 1
                break
    placed = 0
    for along in range(40, 1100, 53):
        for down in (22, 112, 182):
            if placed < 5 and ticks(*wall_point(along, down), *sdir, n=2 + placed % 3):
                placed += 1
                break
    for x_, y_ in ((400, 420), (446, 452), (414, 520)):
        placard(x_ * R.SX, y_ * R.SY, 0.0, 1.0, 26, 11, 1) or ticks(x_ * R.SX, y_ * R.SY, 0.0, 1.0)
    # the white plate on the far end of the beam (reference), and markers
    bx_, by_ = 232 * R.SX + su[0] * 300, 498 * R.SY + su[1] * 300 + 8
    pts = rrect(bx_, by_ - 6, su[0], su[1], 38, 12)
    sym_path(greeb, pts, "Fill Color 222,228,234,200 | Stroke Color 0,0,0,180 | StrokeWidth 1", True)
    sym_path(greeb, [pts[0], pts[1]], "Stroke Color 255,255,255,220 | StrokeWidth 1.2")
    for x_, y_, col in ((420, 452, "255,70,60"), (470, 470, "255,170,60"), (300, 590, "255,70,60"), (160, 300, "255,170,60")):
        marker(x_ * R.SX, y_ * R.SY, col)

    # specular glints: short white streaks along the window rails (left half, mirrored)
    for wp, ln in rail(7):
        L = ln.length
        d = drng.uniform(40, 140)
        while d < L - 40:
            p0, p1 = ln.interpolate(d), ln.interpolate(min(L, d + drng.uniform(16, 46)))
            if p0.x < CW / 2 - 12 and p1.x < CW / 2 - 12 and not Point(p0.x, p0.y).buffer(4).intersects(BUSY):
                seg = [(p0.x, p0.y), (p1.x, p1.y)]
                sym_path(greeb, seg, "Stroke Color 200,225,245,40 | StrokeWidth 5 | StrokeStartCap Round | StrokeEndCap Round")
                sym_path(greeb, seg, f"Stroke Color 245,250,255,{drng.randint(150, 220)} | StrokeWidth 1.5 | StrokeStartCap Round | StrokeEndCap Round")
            d += drng.uniform(160, 340)

    # lower silver rails above the floor hoses (reference: two pale bars rising from the bottom corner)
    for (a_, b_), w_ in ((((196, 648), (300, 612)), 7), (((206, 666), (318, 628)), 5)):
        ln = LineString(C([a_, b_])).intersection(HULL.buffer(-4)).difference(AVOID.buffer(6))
        for seg in lines_of(ln):
            pts = list(seg.coords)
            if seg.length < 40:
                continue
            sym_path(greeb, pts, f"Stroke Color 0,0,0,220 | StrokeWidth {w_ + 4} | StrokeStartCap Round | StrokeEndCap Round")
            sym_path(greeb, pts, f"Stroke Color 96,110,124,255 | StrokeWidth {w_} | StrokeStartCap Round | StrokeEndCap Round")
            sym_path(greeb, [(x_, y_ - w_ * 0.25) for x_, y_ in pts], f"Stroke Color 220,232,242,{150 if w_ > 5 else 110} | StrokeWidth 1.3")

    # small mechanical boxes beside the console (silver top edge, dark body, white tick)
    for (x_, y_, w_, h_) in ((392, 392, 22, 12), (452, 404, 14, 18), (376, 448, 18, 10)):
        X_, Y_, W_, H_ = x_ * R.SX, y_ * R.SY, w_ * R.SX, h_ * R.SY
        g = box(X_, Y_, X_ + W_, Y_ + H_)
        if not (HULL.buffer(-4).contains(g) and not g.intersects(BUSY)):
            continue
        sym_poly(greeb, g, "Fill LinearGradient {G} | Stroke Color 0,0,0,220 | StrokeWidth 1.4", 90,
                 [("70,82,96,255", 0), ("24,28,34,255", 0.25), ("10,12,16,255", 1)])
        sym_path(greeb, [(X_ + 2, Y_ + 1.5), (X_ + W_ - 2, Y_ + 1.5)], "Stroke Color 225,235,245,190 | StrokeWidth 1.4")
        sym_path(greeb, [(X_ + W_ * 0.2, Y_ + H_ * 0.6), (X_ + W_ * 0.45, Y_ + H_ * 0.6)], "Stroke Color 230,236,242,170 | StrokeWidth 2")

    # silver lip along the front edge of the dash (reference: a pale glossy edge across the bottom)
    lip = LineString(C([(452, 703), (808, 703)])).difference(cpoly([(606, 640), (654, 640), (654, 709), (606, 709)]))
    for seg in lines_of(lip):
        pts = list(seg.coords)
        greeb.path(pts, "Stroke Color 0,0,0,200 | StrokeWidth 9")
        greeb.path(pts, "Stroke Color 70,82,96,255 | StrokeWidth 6")
        greeb.path([(x_, y_ - 2) for x_, y_ in pts], "Stroke Color 215,228,240,170 | StrokeWidth 1.4")

    # ---------------------------------------------------------------- strut lights, spill
    for (x, y) in R.LIGHTS:
        X, Y = x * R.SX, y * R.SY
        # a compact lens glow (reference: a small hot lens, little halo) so the white collar stays readable
        for r, a in ((120, 3), (74, 6), (44, 10), (26, 18), (15, 40), (9.5, 95)):
            lights.ellipse(X, Y, r, r, f"Fill Color 50,135,255,{a} | StrokeWidth 0")
        lights.ellipse(X, Y, 85, 1.6, "Fill Color 140,200,255,40 | StrokeWidth 0")
        lights.ellipse(X, Y, 2.0, 22, "Fill Color 140,200,255,30 | StrokeWidth 0")
        lights.ellipse(X, Y, 5, 5, "Fill Color 190,230,255,255 | StrokeWidth 0")
        lights.ellipse(X, Y, 2.4, 2.4, "Fill Color 255,255,255,255 | StrokeWidth 0")
    for (x0, y0, x1, y1) in R.SCREENS:
        cx_, cy_ = (x0 + x1) / 2 * R.SX, (y0 + y1) / 2 * R.SY
        hw, hh = (x1 - x0) / 2 * R.SX, (y1 - y0) / 2 * R.SY
        for i in range(5):
            k = 1.1 + 0.12 * i
            spill.ellipse(cx_, cy_, hw * k, hh * k, f"Fill Color {ACC},3 | StrokeWidth 0")
    for i in range(7):
        k = 1 - i / 7
        spill.ellipse(630 * R.SX, 560 * R.SY, 120 + 260 * k, 40 + 110 * k, f"Fill Color {ACC},3 | StrokeWidth 0")

    # ---------------------------------------------------------------- HUD lines in the theme colour (same bloom as the widgets)
    def neon(pts, w=1.7, glow=True, alpha=235, closed=False):
        if glow:
            decor.path(pts, f"Stroke Color {ACC},(#GlowAlpha#*0.38) | StrokeWidth (#GlowWidth#*{w * 2.1:.2f}) | StrokeLineJoin Round", closed)
            decor.path(pts, f"Stroke Color {ACC},(#GlowAlpha#*0.95) | StrokeWidth (#GlowWidth#*{w:.2f}) | StrokeLineJoin Round", closed)
        decor.path(pts, f"Stroke Color {ACC},{alpha} | StrokeWidth {w:.1f} | StrokeLineJoin Round", closed)
        if glow:
            decor.path(pts, f"Stroke Color 235,250,255,({alpha}*#CoreWhite#*0.8) | StrokeWidth {w * 0.45:.2f} | StrokeLineJoin Round", closed)

    for l in R.CONSOLE_LINES:        # the top console outline (reference: tab trapezoid and both wings)
        neon(C(l))
    neon(C(R.ARCH))
    for l in R.DASH_LINES:           # parallels and outer diagonals under the arch
        neon(C(l), 1.3, True, 190)
    # the two dash screens: a lit pane in the theme colour with a bloom edge (glass, not a black box)
    # (reference: softly lit navy panes - no neon outline, just a faint edge and an inner sheen)
    for (x0, y0, x1, y1) in R.SCREENS:
        pts = C([(x0, y0), (x1, y0), (x1, y1), (x0, y1)])
        decor.path(pts, "Fill LinearGradient {G} | StrokeWidth 0", True,
                   grad(90, ("40,110,200,70", 0), ("30,85,170,52", 0.6), ("40,110,200,64", 1)))
        decor.path(pts, f"Stroke Color {ACC},55 | StrokeWidth 1.2", True)
        decor.path([(p[0], p[1]) for p in C([(x0 + 2, y0 + 2), (x1 - 2, y0 + 2)])], "Stroke Color 200,230,255,40 | StrokeWidth 1.5")
    for t in R.TILTED:
        decor.path(C(t), "Fill LinearGradient {G} | StrokeWidth 0", True,
                   grad(90, ("45,115,205,80", 0), ("30,85,170,55", 1)))
        decor.path(C(t), f"Stroke Color {ACC},60 | StrokeWidth 1.2", True)
    gx, gy = R.CIRCLE_GLYPH
    neon(C([(gx + 8 * math.cos(math.radians(a)), gy + 8 * math.sin(math.radians(a))) for a in range(30, 331, 15)]), 1.8)
    neon(C([(gx - 3, gy - 3), (gx + 2, gy), (gx - 3, gy + 3)]), 1.8)
    x0, x1, yy = R.COWL_DOTS
    for i in range(22):
        xx = (x0 + (x1 - x0) * i / 21) * R.SX
        decor.rect(xx - 5, yy * R.SY - 7, 10, 14, f"Fill Color {ACC},(#GlowAlpha#*0.5) | StrokeWidth 0")
        decor.rect(xx - 2, yy * R.SY - 4, 4, 8, f"Fill Color {ACC},170 | StrokeWidth 0")

    return [hull, frames, greeb], [glass, accents, spill, lights, decor]


def write_glass_gradient():
    p = PARTS / "Glass.inc"
    t = p.read_text()
    t = t.replace("[Glass]\n", "[Glass]\nGlassGrad=90 | #ColorAccent#,(Min(255,#GlassTint#*0.75)) ; 0.0 | #ColorAccent#,(#GlassTint#*0.12) ; 0.55 | #ColorAccent#,(Min(255,#GlassTint#*0.3)) ; 1.0\n", 1)
    p.write_text(t, newline="\r\n")


def write_order():
    def incs(parts):
        return "".join(f"@Include{p}=#CURRENTPATH#Parts\\{p}.inc\n" for p in parts)

    def image(name, file, alpha, hidden=None, note=""):
        return (f"{note}[{name}]\nMeter=Image\nImageName=#@#Images\\{file}\nX=0\nY=0\nW=(2560*#Scale#)\nH=(1600*#Scale#)\n"
                f"PreserveAspectRatio=0\nImageAlpha={alpha}\nHidden=(Clamp(#FrameOff#+({hidden or 0}),0,1))\n\n")

    head = FRAME_INI.read_text().partition("; drawing order")[0]
    body = ("; drawing order: window tint, glass smudges + glare, scanlines, dark tints, hull, picture, live accents\n"
            "[Order]\nMeasure=Calc\nFormula=0\n" + incs(["Glass"]) + "\n"
            + image("GlassFX", "glass_fx.png", "(Clamp(#GlassGlare#*21,0,255))")
            + image("Scan", "scan.png", "(Clamp(#ScanAlpha#*18,0,255))", "(1-#ScanLines#)")
            + image("Shade", "shade.png", "#ShadeAlpha#", note="; soft dark tints where the HUD sits (no boxes)\n")
            + image("Hull", "hull.png", "#HullAlpha#", "#UseShipImage#",
                    note="; the textured hull, pre-rendered by tools/ship_frame.py (windows transparent)\n")
            + image("ShipImage", "#ShipImage#", "#HullAlpha#", "(1-#UseShipImage#)",
                    note="; picture mode (UseShipImage=1): your own cockpit picture, windows cut by tools/image_frame.py\n")
            + image("Mist", "mist.png", "#MistAlpha#",
                    note="; neon mist: wide, very dim light bleeding off the window edges and corner cuts (theme colour)\n").replace(
                        "PreserveAspectRatio=0\n", "PreserveAspectRatio=0\nImageTint=#ColorAccent#\n")
            + image("Corners", "corners.png", "#HullAlpha#", "#UseShipImage#",
                    note="; the visor corner pieces, over the mist so it only spreads inward (frame_render.corners_png)\n")
            + "; live, theme-coloured: rim glow + LEDs, HUD light on the dash, strut lights, HUD lines\n"
            "[OrderOver]\nMeasure=Calc\nFormula=0\n" + incs(["Accents", "Spill", "Lights", "Decor"])
)
    FRAME_INI.write_text(head + body, newline="\r\n")


def write_source(baked):
    """tools/frame_src: a minimal skin holding the baked layers, rasterised by frame_render"""
    for f in SRC_PARTS.glob("*.inc"):
        f.unlink()
    for l in baked:
        l.write(SRC_PARTS)
    (SRC_PARTS.parent / "Frame.ini").write_text(
        "; GENERATED by tools/ship_frame.py - the neutral hull, rasterised into @Resources/Images/hull.png\n"
        "[Rainmeter]\nUpdate=-1\n\n[Variables]\n@IncludeSettings=#@#Settings.inc\nScale=1\n\n"
        "[Order]\nMeasure=Calc\nFormula=0\n" + "".join(f"@Include{l.name}=#CURRENTPATH#Parts\\{l.name}.inc\n" for l in baked),
        newline="\r\n")


def main():
    import frame_render
    PARTS.mkdir(parents=True, exist_ok=True)
    for f in PARTS.glob("*.inc"):
        f.unlink()
    baked, live = build()
    write_source(baked)
    counts = {l.name: l.write() for l in live}
    write_glass_gradient()
    write_order()
    print("baked shapes:", {l.name: len(l) for l in baked})
    print("live shapes:", counts, "total", sum(counts.values()))
    print("images (MB):", frame_render.render())


if __name__ == "__main__":
    main()
