#!/usr/bin/env python3
"""Build the cockpit (Skins/Spaceship/Frame) as Rainmeter Shape meters, symmetric left/right.

The windows come from the owner's line drawing (tools/ref_layout.py WINDOWS). Everything else is designed
here on the left side and mirrored, in the spirit of a real sci-fi cockpit render: gunmetal panels with
cylindrical shading, window frames with gaskets and bolts, lit sills, side walls with grab handles and
blue LED clusters, a centre console with a hologram projector well, corrugated hoses, and recessed
housings behind every instrument that sits on the hull.

Parts written to Frame/Parts (drawing order, see Frame.ini, generated too):
  Glass, Glare, Scan        theme-tinted glass, reflections, optional scanlines        (always)
  Hull                      silhouette + shaded structural panels                      (vector mode)
  [ShipImage]               picture mode, Settings UseShipImage=1 (tools/image_frame.py)
  Frames, Greebles, Lights  window frames, surface detail, strut lights + LEDs         (vector mode)
  Housings, Spill, Decor    instrument housings, HUD light on the dash, HUD lines      (always)

Metal tones are variables (Settings.inc HullDark / HullMid / HullLight / HullEdge), so the shading can be
retuned without regenerating. Usage: python tools/ship_frame.py
"""
import math
import random
import sys
from pathlib import Path

from shapely.affinity import scale as shp_scale
from shapely.geometry import LineString, MultiLineString, MultiPolygon, Point, Polygon, box
from shapely.ops import split, substring, unary_union

sys.path.insert(0, str(Path(__file__).parent))
import ref_layout as R  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PARTS = ROOT / "Skins" / "Spaceship" / "Frame" / "Parts"
FRAME_INI = PARTS.parent / "Frame.ini"
CW, CH = R.CW, R.CH
PER_METER = 150
HEADER = "; GENERATED by tools/ship_frame.py - edit the generator, not this file.\n"

DARK, MID, LIGHT, EDGE = "#HullDark#", "#HullMid#", "#HullLight#", "#HullEdge#"
ACC = "#ColorAccent#"
VECTOR_ONLY = "#UseShipImage#"


# ------------------------------------------------------------------ geometry helpers
def C(pts):
    """reference px -> canvas px"""
    return [(x * R.SX, y * R.SY) for x, y in pts]


def cpoly(pts):
    return Polygon(C(pts)).buffer(0)


def mirror(geom):
    return shp_scale(geom, -1, 1, origin=(CW / 2, 0))


def mpts(pts):
    return [(CW - x, y) for x, y in pts]


def polys_of(g):
    if g.is_empty:
        return []
    if isinstance(g, Polygon):
        return [g]
    return [p for p in getattr(g, "geoms", []) if isinstance(p, Polygon)]


def lines_of(g):
    if g.is_empty:
        return []
    if isinstance(g, LineString):
        return [g]
    if isinstance(g, MultiLineString):
        return list(g.geoms)
    out = []
    for p in getattr(g, "geoms", []):
        out += lines_of(p)
    return out


def hole_free(poly, depth=0):
    """Rainmeter paths have no holes: split polygons with interiors until none remain"""
    if not poly.interiors or depth > 12:
        return [Polygon(poly.exterior)]
    x = poly.interiors[0].centroid.x
    minx, miny, maxx, maxy = poly.bounds
    out = []
    for p in polys_of(split(poly, LineString([(x, miny - 1), (x, maxy + 1)]))):
        out += hole_free(p, depth + 1)
    return out


def norm(vx, vy):
    l = math.hypot(vx, vy) or 1.0
    return vx / l, vy / l


def at(A, B, t):
    return (A[0] + (B[0] - A[0]) * t, A[1] + (B[1] - A[1]) * t)


def grad(angle, *stops):
    return f"{angle:.0f} | " + " | ".join(f"{c} ; {o:.2f}" for c, o in stops)


# ------------------------------------------------------------------ output
class Layer:
    """Shapes for one part file, split over meters of PER_METER shapes. '{G}' in a spec is replaced by the
    shape's own gradient option name."""

    def __init__(self, name, hidden=None):
        self.name, self.hidden, self.items = name, hidden, []

    def path(self, pts, spec, closed=False, gradient=None):
        if len(pts) < 2:
            return
        d = " | ".join(("%.1f,%.1f" if i == 0 else "LineTo %.1f,%.1f") % p for i, p in enumerate(pts))
        if "Fill " not in spec:
            spec = "Fill Color 0,0,0,0 | " + spec     # Rainmeter fills every path white unless told otherwise
        self.items.append(("path", d + (" | ClosePath 1" if closed else ""), spec, gradient))

    def poly(self, geom, spec, gradient=None):
        for p in polys_of(geom):
            for q in hole_free(p):
                if q.area > 2:
                    self.path(list(q.exterior.coords)[:-1], spec, True, gradient)

    def line(self, geom, spec):
        for ln in lines_of(geom):
            self.path(list(ln.coords), spec)

    def raw(self, spec):
        self.items.append(("raw", None, spec, None))

    def ellipse(self, x, y, rx, ry, spec):
        self.raw(f"Ellipse {x:.1f},{y:.1f},{rx:.1f},{ry:.1f} | {spec}")

    def rect(self, x, y, w, h, spec, r=0):
        self.raw(f"Rectangle {x:.1f},{y:.1f},{w:.1f},{h:.1f}{',%.1f' % r if r else ''} | {spec}")

    def write(self):
        chunks = [self.items[i:i + PER_METER] for i in range(0, len(self.items), PER_METER)] or [[]]
        out = []
        for n, chunk in enumerate(chunks, 1):
            name = self.name if len(chunks) == 1 else f"{self.name}{n:02d}"
            lines = [f"[{name}]", "Meter=Shape", "X=0", "Y=0"]
            if not chunk:
                lines.append("Shape=Rectangle 0,0,0,0 | Fill Color 0,0,0,0 | StrokeWidth 0")
            for k, (kind, d, spec, gradient) in enumerate(chunk, 1):
                key = "Shape" if k == 1 else f"Shape{k}"
                if gradient:
                    lines.append(f"G{k}={gradient}")
                    spec = spec.replace("{G}", f"G{k}")
                if kind == "path":
                    lines.append(f"P{k}={d}")
                    lines.append(f"{key}=Path P{k} | {spec}")
                else:
                    lines.append(f"{key}={spec}")
            lines.append("TransformationMatrix=#Scale#;0;0;#Scale#;0;0")
            if self.hidden:
                lines.append(f"Hidden={self.hidden}")
            lines.append("DynamicVariables=0")
            out.append("\n".join(lines) + "\n")
        (PARTS / f"{self.name}.inc").write_text(HEADER + "\n".join(out), newline="\r\n")
        return len(self.items)


def sym_poly(layer, geom, spec, angle=None, stops=None):
    """left-side polygon + its mirror; a gradient angle is mirrored with it"""
    layer.poly(geom, spec, grad(angle, *stops) if stops else None)
    layer.poly(mirror(geom), spec, grad(180 - angle, *stops) if stops else None)


def sym_path(layer, pts, spec, closed=False):
    layer.path(pts, spec, closed)
    layer.path(mpts(pts), spec, closed)


# ------------------------------------------------------------------ the ship
SCREEN = box(0, 0, CW, CH)
WINDOWS = unary_union([cpoly(w) for w in R.WINDOWS])
HULL = SCREEN.difference(WINDOWS)
ZONES = {z["id"]: Polygon(z["quad"]) for z in R.ZONES}
BUSY = unary_union(list(ZONES.values()) + [Point(*C([l])[0]).buffer(60) for l in R.LIGHTS]).buffer(10)

PILLAR = cpoly(R.PILLAR_L)
STRUT = cpoly(R.STRUT_L)
SILL_EDGE = C(R.SILL_EDGE_L)
# centre console (trapezoid widening to the floor) and the cowl under the windscreen
COWL = cpoly([(500.8, 365.5), (759.2, 365.5), (776, 393), (484, 393)])
CONSOLE = cpoly([(484, 393), (776, 393), (905, 709), (355, 709)])
# zones that are projected on the glass / are their own instrument; they never get a housing
NO_HOUSING = {"C_target", "C_hud", "C_sphere"}


def member_axis(poly_pts, a, b):
    A, B = C([a])[0], C([b])[0]
    ax = norm(B[0] - A[0], B[1] - A[1])
    return A, B, ax, (-ax[1], ax[0])


def cylinder(angle):
    """stops for a rounded metal member: dark edges, bright ridge a little off-centre"""
    return grad(angle, (f"{DARK},255", 0), (f"{MID},255", 0.28), (f"{LIGHT},255", 0.42), (f"{MID},255", 0.62), (f"{DARK},255", 1))


def build():
    rng = random.Random(11)
    hull = Layer("Hull", hidden=VECTOR_ONLY)
    frames = Layer("Frames", hidden=VECTOR_ONLY)
    greeb = Layer("Greebles", hidden=VECTOR_ONLY)
    lights = Layer("Lights", hidden=VECTOR_ONLY)
    housing = Layer("Housings")
    spill = Layer("Spill")
    glass = Layer("Glass")
    glare = Layer("Glare")
    scan = Layer("Scan", hidden="(1-#ScanLines#)")
    decor = Layer("Decor")

    # ---------------------------------------------------------------- glass
    for w in R.WINDOWS:
        glass.path(C(w), "Fill LinearGradient GlassGrad | StrokeWidth 0", True)

    # ---------------------------------------------------------------- hull: silhouette, then shaded members
    hull.poly(HULL, "Fill LinearGradient {G} | StrokeWidth 0",
              grad(90, (f"{DARK},255", 0), (f"{MID},255", 0.5), (f"{DARK},255", 1)))
    left = box(0, 0, CW / 2, CH)
    # ceiling band: darker up top, catching light toward the windscreen
    ceil = box(0, 0, CW / 2, 92 * R.SY + 2).intersection(HULL).difference(STRUT)
    sym_poly(hull, ceil, "Fill LinearGradient {G} | StrokeWidth 0", 90,
             [(f"{DARK},255", 0), (f"{MID},255", 0.75), (f"{LIGHT},255", 1)])
    # A-pillar and roof strut, shaded as rounded members across their width
    for pts, a, b in ((R.PILLAR_L, (275.4, 90), (489, 371.5)), (R.STRUT_L, (180, 63), (0, 242))):
        A, B, ax, n = member_axis(pts, a, b)
        g, ang = cpoly(pts).intersection(HULL), math.degrees(math.atan2(n[1], n[0]))
        hull.poly(g, "Fill LinearGradient {G} | StrokeWidth 0", cylinder(ang))
        hull.poly(mirror(g), "Fill LinearGradient {G} | StrokeWidth 0", cylinder(180 - ang))
    # side wall below the side window: bands running parallel to the sill
    e0, e1 = SILL_EDGE[0], SILL_EDGE[1]
    sx, sy = norm(e1[0] - e0[0], e1[1] - e0[1])
    sn = (-sy, sx)                                                # normal pointing down into the wall
    if sn[1] < 0:
        sn = (-sn[0], -sn[1])
    wall = HULL.intersection(left).difference(CONSOLE).difference(COWL).difference(PILLAR)
    wall = wall.difference(Polygon([(0, 0), (CW / 2, 0), (CW / 2, e1[1]), e1, e0, (0, e0[1])]))
    sill_ang = math.degrees(math.atan2(sn[1], sn[0]))
    bands = [(0, 30, [(f"{LIGHT},255", 0), (f"{MID},255", 0.45), (f"{DARK},255", 1)]),        # lit sill top
             (30, 150, [(f"{MID},255", 0), (f"{DARK},255", 1)]),                                # upper wall panel
             (150, 290, [(f"{DARK},255", 0), (f"{MID},235", 0.5), (f"{DARK},255", 1)]),          # lower wall panel
             (290, 900, [(f"{DARK},255", 0), (f"0,0,0,255", 1)])]                               # floor shadow
    band_lines = []
    for d0, d1, stops in bands:
        strip = Polygon([(e0[0] - sx * 3000 + sn[0] * d0, e0[1] - sy * 3000 + sn[1] * d0),
                         (e0[0] + sx * 3000 + sn[0] * d0, e0[1] + sy * 3000 + sn[1] * d0),
                         (e0[0] + sx * 3000 + sn[0] * d1, e0[1] + sy * 3000 + sn[1] * d1),
                         (e0[0] - sx * 3000 + sn[0] * d1, e0[1] - sy * 3000 + sn[1] * d1)])
        sym_poly(hull, wall.intersection(strip), "Fill LinearGradient {G} | StrokeWidth 0", sill_ang, stops)
        if d0 > 0:
            band_lines.append(d0)
    # console and cowl
    hull.poly(CONSOLE, "Fill LinearGradient {G} | StrokeWidth 0",
              grad(90, (f"{MID},255", 0), (f"{DARK},255", 0.55), (f"0,0,0,255", 1)))
    hull.poly(COWL, "Fill LinearGradient {G} | StrokeWidth 0",
              grad(90, (f"{LIGHT},255", 0), (f"{MID},255", 0.4), (f"{DARK},255", 1)))
    # console side bevels
    for pts in (C([(484, 393), (355, 709)]), ):
        sym_path(hull, pts, f"Stroke Color {LIGHT},150 | StrokeWidth 2.2")
        sym_path(hull, [(x + 6, y) for x, y in pts], "Stroke Color 0,0,0,170 | StrokeWidth 3")
    hull.path(C([(484, 393), (776, 393)]), "Stroke Color 0,0,0,180 | StrokeWidth 3")
    hull.path(C([(500.8, 366.5), (759.2, 366.5)]), f"Stroke Color {EDGE},170 | StrokeWidth 2")
    # wall seams between the bands (groove + lit lip), clipped off widgets
    for d in band_lines[:2]:
        ln = LineString([(e0[0] - sx * 3000 + sn[0] * d, e0[1] - sy * 3000 + sn[1] * d),
                         (e0[0] + sx * 3000 + sn[0] * d, e0[1] + sy * 3000 + sn[1] * d)]).intersection(wall)
        for seg in lines_of(ln):
            pts = list(seg.coords)
            sym_path(hull, pts, "Stroke Color 0,0,0,190 | StrokeWidth 3")
            sym_path(hull, [(x + sn[0] * 2.5, y + sn[1] * 2.5) for x, y in pts], f"Stroke Color {LIGHT},110 | StrokeWidth 1.2")

    # wall panel cuts across the bands, each with a pair of rivets
    for along in range(260, 1100, 290):
        p0, p1 = (e0[0] + sx * along + sn[0] * 34, e0[1] + sy * along + sn[1] * 34), (e0[0] + sx * along + sn[0] * 290, e0[1] + sy * along + sn[1] * 290)
        seg = LineString([p0, p1]).intersection(wall.buffer(-8)).difference(BUSY)
        for s_ in lines_of(seg):
            pts = list(s_.coords)
            sym_path(hull, pts, "Stroke Color 0,0,0,180 | StrokeWidth 2.6")
            sym_path(hull, [(x + 2.2, y) for x, y in pts], f"Stroke Color {LIGHT},70 | StrokeWidth 1")

    # ---------------------------------------------------------------- window frames: bezel, gasket, rim light, bolts
    light_dir = norm(0, -1.0)
    for w in R.WINDOWS:
        wp = cpoly(w)
        outer = wp.buffer(11, join_style=2).exterior
        frames.line(outer.intersection(SCREEN.buffer(-1)), f"Stroke Color {MID},255 | StrokeWidth 18 | StrokeLineJoin Miter")
        frames.line(wp.buffer(19.5, join_style=2).exterior.intersection(SCREEN.buffer(-1)), "Stroke Color 0,0,0,170 | StrokeWidth 2.2 | StrokeLineJoin Miter")
        frames.line(wp.buffer(17.5, join_style=2).exterior.intersection(SCREEN.buffer(-1)), f"Stroke Color {LIGHT},90 | StrokeWidth 1.2 | StrokeLineJoin Miter")
        frames.line(wp.buffer(3, join_style=2).exterior.intersection(SCREEN.buffer(-1)), "Stroke Color 0,0,0,230 | StrokeWidth 4 | StrokeLineJoin Miter")
        # rim light on the inner lip, brighter where the edge faces up toward the sky
        pts = list(wp.buffer(1.2, join_style=2).exterior.coords)
        for i in range(len(pts) - 1):
            (x0, y0), (x1, y1) = pts[i], pts[i + 1]
            ex, ey = norm(x1 - x0, y1 - y0)
            nx, ny = ey, -ex
            lit = 0.3 + 0.7 * max(0.0, -(nx * light_dir[0] + ny * light_dir[1]))
            seg = LineString([(x0, y0), (x1, y1)]).intersection(SCREEN.buffer(-1))
            frames.line(seg, f"Stroke Color {ACC},{int(22 * lit)} | StrokeWidth 8")
            frames.line(seg, f"Stroke Color {EDGE},{int(60 + 150 * lit)} | StrokeWidth {1.0 + lit:.1f}")
        # bolts along the bezel
        ring = wp.buffer(11, join_style=2).exterior
        d = 30.0
        while d < ring.length:
            p = ring.interpolate(d)
            d += 74
            if not SCREEN.buffer(-8).contains(p):
                continue
            frames.ellipse(p.x, p.y, 3.4, 3.4, f"Fill Color {DARK},255 | Stroke Color 0,0,0,200 | StrokeWidth 1")
            frames.ellipse(p.x - 0.8, p.y - 0.9, 1.4, 1.4, f"Fill Color {EDGE},150 | StrokeWidth 0")

    # ---------------------------------------------------------------- pillar / strut detail
    members = [(R.PILLAR_L, (275.4, 90), (489, 371.5), (0.2, 0.62, 0.86), (0.7, 0.8)),
               (R.STRUT_L, (180, 63), (0, 242), (0.3, 0.75), None)]
    for pts, a, b, seams, vent in members:
        poly = cpoly(pts).intersection(HULL)
        A, B, ax, n = member_axis(pts, a, b)
        for side in (0, 1):
            P_ = poly if side == 0 else mirror(poly)
            A_ = A if side == 0 else (CW - A[0], A[1])
            B_ = B if side == 0 else (CW - B[0], B[1])
            ax_ = ax if side == 0 else (-ax[0], ax[1])
            n_ = n if side == 0 else (-n[0], n[1])
            for off, spec in ((-24, "Stroke Color 0,0,0,130 | StrokeWidth 1.8"), (-25.8, f"Stroke Color {LIGHT},45 | StrokeWidth 0.8")):
                for p in polys_of(P_.buffer(off, join_style=2)):
                    greeb.line(p.exterior.difference(BUSY), spec)
            for t in seams:
                c = at(A_, B_, t)
                seg = LineString([(c[0] - n_[0] * 400, c[1] - n_[1] * 400), (c[0] + n_[0] * 400, c[1] + n_[1] * 400)]).intersection(P_.buffer(-14))
                for s in lines_of(seg):
                    if s.intersects(BUSY):
                        continue
                    p0, p1 = s.coords[0], s.coords[-1]
                    greeb.path([p0, p1], "Stroke Color 0,0,0,190 | StrokeWidth 2.6")
                    greeb.path([(p0[0] + ax_[0] * 2.4, p0[1] + ax_[1] * 2.4), (p1[0] + ax_[0] * 2.4, p1[1] + ax_[1] * 2.4)],
                               f"Stroke Color {LIGHT},90 | StrokeWidth 1")
                    for q in (p0, p1):
                        greeb.ellipse(q[0] + ax_[0] * 8, q[1] + ax_[1] * 8, 2.6, 2.6, f"Fill Color {DARK},255 | Stroke Color 0,0,0,200 | StrokeWidth 0.8")
            if vent:
                c0, c1 = at(A_, B_, vent[0]), at(A_, B_, vent[1])
                plate = P_.buffer(-28).intersection(LineString([c0, c1]).buffer(40, cap_style=2))
                if plate.geom_type == "Polygon" and not plate.intersects(BUSY) and plate.area > 200:
                    greeb.poly(plate, "Fill Color 0,0,0,110 | Stroke Color 0,0,0,180 | StrokeWidth 1.4")
                    m = max(4, int(math.dist(c0, c1) / 10))
                    for i in range(m):
                        c = at(c0, c1, (i + 0.5) / m)
                        seg = LineString([(c[0] - n_[0] * 200, c[1] - n_[1] * 200), (c[0] + n_[0] * 200, c[1] + n_[1] * 200)]).intersection(plate.buffer(-5))
                        for s in lines_of(seg):
                            p0, p1 = s.coords[0], s.coords[-1]
                            greeb.path([p0, p1], "Stroke Color 0,0,0,230 | StrokeWidth 3.4 | StrokeStartCap Round | StrokeEndCap Round")
                            greeb.path([(p0[0] + ax_[0] * 2.4, p0[1] + ax_[1] * 2.4), (p1[0] + ax_[0] * 2.4, p1[1] + ax_[1] * 2.4)],
                                       f"Stroke Color {LIGHT},60 | StrokeWidth 1")

    # ---------------------------------------------------------------- side walls: grab handles, LED clusters, vents
    def wall_point(d_along, d_down):
        return (e0[0] + sx * d_along + sn[0] * d_down, e0[1] + sy * d_along + sn[1] * d_down)

    def handle(p0, p1):
        for side in (0, 1):
            q0, q1 = (p0, p1) if side == 0 else ((CW - p0[0], p0[1]), (CW - p1[0], p1[1]))
            bar = [q0, q1]
            greeb.path(bar, "Stroke Color 0,0,0,170 | StrokeWidth 15 | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path(bar, f"Stroke Color {MID},255 | StrokeWidth 10 | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path([(x, y - 2.2) for x, y in bar], f"Stroke Color {EDGE},150 | StrokeWidth 2.4 | StrokeStartCap Round | StrokeEndCap Round")
            for q in (q0, q1):
                greeb.rect(q[0] - 9, q[1] - 6, 18, 16, f"Fill Color {DARK},255 | Stroke Color 0,0,0,200 | StrokeWidth 1.2", 2)
                greeb.ellipse(q[0], q[1] + 2, 2.4, 2.4, f"Fill Color {LIGHT},160 | StrokeWidth 0")

    def leds(x, y, cols, rows, seed):
        r = random.Random(seed)
        for side in (0, 1):
            ox = x if side == 0 else CW - x - cols * 13
            greeb.rect(ox - 6, y - 6, cols * 13 + 9, rows * 10 + 9, "Fill Color 0,0,0,150 | Stroke Color 0,0,0,200 | StrokeWidth 1", 2)
            for i in range(cols):
                for j in range(rows):
                    on = r.random()
                    a = 255 if on > 0.55 else (110 if on > 0.2 else 40)
                    cx, cy = ox + i * 13, y + j * 10
                    if a == 255:
                        lights.rect(cx - 4, cy - 4, 15, 12, f"Fill Color {ACC},34 | StrokeWidth 0", 4)
                    lights.rect(cx, cy, 7, 4, f"Fill Color {ACC},{a} | StrokeWidth 0", 1)

    taken = []

    def free(x, y=None, w=None, h=None):
        g = x if y is None else box(x, y, x + w, y + h)
        return (HULL.buffer(-6).contains(g) and not g.intersects(BUSY) and g.intersects(wall)
                and not any(g.buffer(30).intersects(t) for t in taken))

    for along in [150] + list(range(0, 900, 40)):
        q0, q1 = wall_point(along, 95), wall_point(along + 260, 95)
        bar = LineString([q0, q1]).buffer(14)
        if free(bar):
            handle(q0, q1)
            taken.append(bar)
            break
    for along in range(120, 1000, 30):
        for down in (70, 120, 200, 250):
            p = wall_point(along, down)
            cols, rows = rng.choice((4, 5, 6)), rng.choice((1, 2, 3))
            if len(taken) < 4 and free(p[0] - 8, p[1] - 8, cols * 13 + 14, rows * 10 + 14):
                leds(p[0], p[1], cols, rows, along * 7 + down)
                taken.append(box(p[0] - 8, p[1] - 8, p[0] + cols * 13 + 6, p[1] + rows * 10 + 6))
                break
    # ---------------------------------------------------------------- console: projector well, button banks, hazard edge
    cx, wy = 630 * R.SX, 588 * R.SY
    for rx, ry, spec in ((240, 52, f"Fill Color 0,0,0,200 | Stroke Color {LIGHT},90 | StrokeWidth 2"),
                         (205, 42, f"Fill Color {DARK},255 | Stroke Color 0,0,0,220 | StrokeWidth 3"),
                         (170, 33, f"Fill Color 0,0,0,230 | Stroke Color {ACC},120 | StrokeWidth 2"),
                         (120, 22, f"Fill Color 0,6,12,255 | Stroke Color {ACC},200 | StrokeWidth 2.5")):
        hull.ellipse(cx, wy, rx, ry, spec)
    for k in range(24):
        a = k / 24 * math.tau
        x0, y0 = cx + math.cos(a) * 178, wy + math.sin(a) * 36
        x1, y1 = cx + math.cos(a) * 196, wy + math.sin(a) * 40
        hull.path([(x0, y0), (x1, y1)], f"Stroke Color {LIGHT},80 | StrokeWidth 1.4")
    spill.ellipse(cx, wy, 150, 26, f"Fill Color {ACC},28 | StrokeWidth 0")
    spill.ellipse(cx, wy, 95, 15, f"Fill Color {ACC},60 | StrokeWidth 0")
    spill.ellipse(cx, wy, 40, 6, "Fill Color 220,250,255,140 | StrokeWidth 0")
    # hazard chevrons along the cowl corners
    for x0 in (492, 742):
        strip = cpoly([(x0, 381), (x0 + 26, 381), (x0 + 26, 390), (x0, 390)])
        if strip.intersects(BUSY):
            continue
        hull.poly(strip, "Fill Color 12,12,10,220 | StrokeWidth 0")
        for i in range(6):
            q = Polygon([(x0 * R.SX + i * 9, 390 * R.SY), (x0 * R.SX + i * 9 + 5, 390 * R.SY),
                         (x0 * R.SX + i * 9 + 13, 381 * R.SY), (x0 * R.SX + i * 9 + 8, 381 * R.SY)]).intersection(strip)
            hull.poly(q, "Fill Color #ColorWarn#,110 | StrokeWidth 0")

    # ---------------------------------------------------------------- corrugated hoses along the floor
    def hose(pts, width):
        path = LineString(pts)
        for side in (0, 1):
            P_ = path if side == 0 else LineString(mpts(list(path.coords)))
            c = list(P_.coords)
            greeb.path(c, f"Stroke Color 0,0,0,220 | StrokeWidth {width + 6} | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path(c, f"Stroke Color {DARK},255 | StrokeWidth {width} | StrokeStartCap Round | StrokeEndCap Round")
            greeb.path([(x, y - width * 0.22) for x, y in c], f"Stroke Color {MID},255 | StrokeWidth {width * 0.35:.1f}")
            d = 6.0
            while d < P_.length:
                p, q = P_.interpolate(d), P_.interpolate(min(P_.length, d + 1))
                tx, ty = norm(q.x - p.x, q.y - p.y)
                nx, ny = -ty, tx
                h = width / 2
                greeb.path([(p.x - nx * h, p.y - ny * h), (p.x + nx * h, p.y + ny * h)], "Stroke Color 0,0,0,200 | StrokeWidth 2.2")
                greeb.path([(p.x - nx * h + tx * 2.5, p.y - ny * h + ty * 2.5), (p.x + nx * h + tx * 2.5, p.y + ny * h + ty * 2.5)],
                           f"Stroke Color {LIGHT},70 | StrokeWidth 1")
                d += 11

    hose(C([(150, 712), (230, 688), (310, 684), (352, 700), (365, 712)]), 26)
    hose(C([(60, 715), (120, 694), (210, 676), (250, 664)]), 18)

    # ---------------------------------------------------------------- instrument housings behind hull widgets
    hull_frac = {}
    for zid, zp in ZONES.items():
        hull_frac[zid] = zp.intersection(HULL).area / max(1.0, zp.area)
        if zid in NO_HOUSING or hull_frac[zid] < 0.3:
            continue
        outer = zp.buffer(12, join_style=2)
        bez = outer.buffer(-0.01)
        housing.poly(bez, "Fill LinearGradient {G} | Stroke Color 0,0,0,220 | StrokeWidth 2",
                     grad(90, (f"{LIGHT},255", 0), (f"{MID},255", 0.25), (f"{DARK},255", 1)))
        housing.poly(zp.buffer(5, join_style=2), f"Fill Color 2,7,12,236 | Stroke Color {ACC},60 | StrokeWidth 1.2")
        minx, miny, maxx, maxy = outer.bounds
        if maxx - minx > 90 and maxy - miny > 50:
            for (bx, by) in ((minx + 6, miny + 6), (maxx - 6, miny + 6), (minx + 6, maxy - 6), (maxx - 6, maxy - 6)):
                if outer.contains(Point(bx, by)):
                    housing.ellipse(bx, by, 2.2, 2.2, f"Fill Color {DARK},255 | Stroke Color {EDGE},90 | StrokeWidth 0.8")

    # ---------------------------------------------------------------- strut lights, spill
    for (x, y) in R.LIGHTS:
        X, Y = x * R.SX, y * R.SY
        lights.ellipse(X, Y, 22, 22, f"Fill Color {DARK},255 | Stroke Color 0,0,0,220 | StrokeWidth 2")
        lights.ellipse(X, Y, 15, 15, "Fill Color 10,30,60,255 | StrokeWidth 0")
        for r, a in ((190, 4), (130, 7), (85, 12), (46, 20), (34, 34), (24, 60), (15, 110)):
            lights.ellipse(X, Y, r, r, f"Fill Color 50,135,255,{a} | StrokeWidth 0")
        lights.ellipse(X, Y, 230, 2.2, "Fill Color 120,190,255,30 | StrokeWidth 0")
        lights.ellipse(X, Y, 120, 3.5, "Fill Color 140,200,255,55 | StrokeWidth 0")
        lights.ellipse(X, Y, 2.0, 55, "Fill Color 140,200,255,30 | StrokeWidth 0")
        lights.ellipse(X, Y, 7, 7, "Fill Color 190,230,255,255 | StrokeWidth 0")
        lights.ellipse(X, Y, 3.2, 3.2, "Fill Color 255,255,255,255 | StrokeWidth 0")
    for (x0, y0, x1, y1) in R.SCREENS:
        cx_, cy_ = (x0 + x1) / 2 * R.SX, (y0 + y1) / 2 * R.SY
        hw, hh = (x1 - x0) / 2 * R.SX, (y1 - y0) / 2 * R.SY
        for i in range(5):
            k = 1.1 + 0.12 * i
            spill.ellipse(cx_, cy_, hw * k, hh * k, f"Fill Color {ACC},3 | StrokeWidth 0")
    for i in range(7):
        k = 1 - i / 7
        spill.ellipse(630 * R.SX, 560 * R.SY, 120 + 260 * k, 40 + 110 * k, f"Fill Color {ACC},3 | StrokeWidth 0")

    # ---------------------------------------------------------------- glass reflections and scanlines
    for w in R.WINDOWS:
        wp = cpoly(w)
        minx, miny, maxx, maxy = wp.bounds
        W, H = maxx - minx, maxy - miny
        for (u0, v0), (u1, v1), half, k in (((-0.15, 0.0), (0.55, 1.0), 0.07, 1.0), ((0.25, 0.0), (0.95, 1.0), 0.035, 0.6)):
            p0, p1 = (minx + W * u0, miny + H * v0), (minx + W * u1, miny + H * v1)
            strip = LineString([p0, p1]).buffer(max(W, H) * half, cap_style=2).intersection(wp.buffer(-2))
            dx, dy = norm(p1[0] - p0[0], p1[1] - p0[1])
            ang = math.degrees(math.atan2(dx, -dy))
            for g in polys_of(strip):
                if g.area > 400:
                    glare.poly(g, "Fill LinearGradient {G} | StrokeWidth 0",
                               grad(ang, ("220,240,255,0", 0), (f"220,240,255,(#GlassGlare#*{k})", 0.5), ("220,240,255,0", 1)))
    y = 2.5
    while y < CH:
        scan.line(LineString([(0, y), (CW, y)]).intersection(WINDOWS.buffer(-1)), "Stroke Color 0,0,0,#ScanAlpha# | StrokeWidth 1.6")
        y += 5

    # ---------------------------------------------------------------- HUD lines in the theme colour (same bloom as the widgets)
    def neon(pts, w=1.7, glow=True, alpha=235, closed=False):
        if glow:
            decor.path(pts, f"Stroke Color {ACC},(#GlowAlpha#*0.38) | StrokeWidth (#GlowWidth#*{w * 2.1:.2f}) | StrokeLineJoin Round", closed)
            decor.path(pts, f"Stroke Color {ACC},(#GlowAlpha#*0.95) | StrokeWidth (#GlowWidth#*{w:.2f}) | StrokeLineJoin Round", closed)
        decor.path(pts, f"Stroke Color {ACC},{alpha} | StrokeWidth {w:.1f} | StrokeLineJoin Round", closed)
        if glow:
            decor.path(pts, f"Stroke Color 235,250,255,({alpha}*#CoreWhite#*0.8) | StrokeWidth {w * 0.45:.2f} | StrokeLineJoin Round", closed)

    # (the reference's console outline lines are left out: the instruments now sit in their own housings)
    neon(C(R.ARCH))
    neon(C([(x, y + 22 / R.SY) for x, y in R.ARCH][1:-1]), 1.2, False, 150)
    for t in R.TILTED:
        decor.path(C(t), f"Fill Color {ACC},60 | StrokeWidth 0", True)
        neon(C(t), 1.3, True, 180, closed=True)
        a, b, c, d4 = t
        for i in range(1, 8):
            v = i / 9
            l0 = (a[0] + (d4[0] - a[0]) * v, a[1] + (d4[1] - a[1]) * v)
            r0 = (b[0] + (c[0] - b[0]) * v, b[1] + (c[1] - b[1]) * v)
            ww = 0.35 + 0.08 * ((i * 37) % 7)
            neon(C([(l0[0] + (r0[0] - l0[0]) * 0.15, l0[1] + (r0[1] - l0[1]) * 0.15),
                    (l0[0] + (r0[0] - l0[0]) * (0.15 + ww), l0[1] + (r0[1] - l0[1]) * (0.15 + ww))]), 1, False, 140)
    for (x, y) in R.GLYPHS:
        s = 7
        neon(C([(x - s, y - 3), (x - s, y - s), (x - 3, y - s)]), 1.5)
        neon(C([(x + s, y + 3), (x + s, y + s), (x + 3, y + s)]), 1.5)
        neon(C([(x - 4, y + 2), (x, y - 2), (x + 4, y + 2)]), 1.5)
    gx, gy = R.CIRCLE_GLYPH
    neon(C([(gx + 8 * math.cos(math.radians(a)), gy + 8 * math.sin(math.radians(a))) for a in range(30, 331, 15)]), 1.8)
    neon(C([(gx - 3, gy - 3), (gx + 2, gy), (gx - 3, gy + 3)]), 1.8)
    x0, x1, yy = R.COWL_DOTS
    for i in range(22):
        xx = (x0 + (x1 - x0) * i / 21) * R.SX
        decor.rect(xx - 5, yy * R.SY - 7, 10, 14, f"Fill Color {ACC},(#GlowAlpha#*0.5) | StrokeWidth 0")
        decor.rect(xx - 2, yy * R.SY - 4, 4, 8, f"Fill Color {ACC},170 | StrokeWidth 0")

    return [glass, glare, scan, hull, frames, greeb, lights, housing, spill, decor], hull_frac


def write_glass_gradient():
    p = PARTS / "Glass.inc"
    t = p.read_text()
    t = t.replace("[Glass]\n", "[Glass]\nGlassGrad=90 | #ColorAccent#,(Min(255,#GlassTint#*0.75)) ; 0.0 | #ColorAccent#,(#GlassTint#*0.12) ; 0.55 | #ColorAccent#,(Min(255,#GlassTint#*0.3)) ; 1.0\n", 1)
    p.write_text(t, newline="\r\n")


def write_order():
    under = ["Glass", "Glare", "Scan", "Hull"]
    over = ["Frames", "Greebles", "Housings", "Spill", "Lights", "Decor"]

    def incs(parts):
        return "".join(f"@Include{p}=#CURRENTPATH#Parts\\{p}.inc\n" for p in parts)

    head = FRAME_INI.read_text().partition("; drawing order")[0]
    body = ("; drawing order: glass tint, glare, scanlines, shaded hull\n"
            "[Order]\nMeasure=Calc\nFormula=0\n" + incs(under) + "\n"
            "; picture mode (Settings.inc UseShipImage=1): a cockpit picture with the windows cut out, made by\n"
            "; tools/image_frame.py. The vector hull, frames, detail and lights hide; glass, housings, HUD light and lines stay.\n"
            "[ShipImage]\nMeter=Image\nImageName=#@#Images\\#ShipImage#\nX=0\nY=0\nW=(2560*#Scale#)\nH=(1600*#Scale#)\n"
            "PreserveAspectRatio=0\nHidden=(1-#UseShipImage#)\n\n"
            "; over the hull: window frames, surface detail, instrument housings, HUD light spill, lights, HUD lines\n"
            "[OrderOver]\nMeasure=Calc\nFormula=0\n" + incs(over))
    FRAME_INI.write_text(head + body, newline="\r\n")


def main():
    PARTS.mkdir(parents=True, exist_ok=True)
    for f in PARTS.glob("*.inc"):
        f.unlink()
    layers, hull_frac = build()
    counts = {l.name: l.write() for l in layers}
    write_glass_gradient()
    write_order()
    print("shapes per part:", counts, "total", sum(counts.values()))
    print("housed zones:", sorted(z for z, f in hull_frac.items() if f >= 0.3 and z not in NO_HOUSING))


if __name__ == "__main__":
    main()
